// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln
{
    [CplnResourceType("cpln:index/domainRoute:DomainRoute")]
    public partial class DomainRoute : global::Pulumi.CustomResource
    {
        [Output("domainLink")]
        public Output<string> DomainLink { get; private set; } = null!;

        [Output("domainPort")]
        public Output<int?> DomainPort { get; private set; } = null!;

        [Output("hostPrefix")]
        public Output<string?> HostPrefix { get; private set; } = null!;

        [Output("port")]
        public Output<int?> Port { get; private set; } = null!;

        [Output("prefix")]
        public Output<string> Prefix { get; private set; } = null!;

        [Output("replacePrefix")]
        public Output<string?> ReplacePrefix { get; private set; } = null!;

        [Output("workloadLink")]
        public Output<string> WorkloadLink { get; private set; } = null!;


        /// <summary>
        /// Create a DomainRoute resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DomainRoute(string name, DomainRouteArgs args, CustomResourceOptions? options = null)
            : base("cpln:index/domainRoute:DomainRoute", name, args ?? new DomainRouteArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DomainRoute(string name, Input<string> id, DomainRouteState? state = null, CustomResourceOptions? options = null)
            : base("cpln:index/domainRoute:DomainRoute", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DomainRoute resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DomainRoute Get(string name, Input<string> id, DomainRouteState? state = null, CustomResourceOptions? options = null)
        {
            return new DomainRoute(name, id, state, options);
        }
    }

    public sealed class DomainRouteArgs : global::Pulumi.ResourceArgs
    {
        [Input("domainLink", required: true)]
        public Input<string> DomainLink { get; set; } = null!;

        [Input("domainPort")]
        public Input<int>? DomainPort { get; set; }

        [Input("hostPrefix")]
        public Input<string>? HostPrefix { get; set; }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("prefix", required: true)]
        public Input<string> Prefix { get; set; } = null!;

        [Input("replacePrefix")]
        public Input<string>? ReplacePrefix { get; set; }

        [Input("workloadLink", required: true)]
        public Input<string> WorkloadLink { get; set; } = null!;

        public DomainRouteArgs()
        {
        }
        public static new DomainRouteArgs Empty => new DomainRouteArgs();
    }

    public sealed class DomainRouteState : global::Pulumi.ResourceArgs
    {
        [Input("domainLink")]
        public Input<string>? DomainLink { get; set; }

        [Input("domainPort")]
        public Input<int>? DomainPort { get; set; }

        [Input("hostPrefix")]
        public Input<string>? HostPrefix { get; set; }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        [Input("replacePrefix")]
        public Input<string>? ReplacePrefix { get; set; }

        [Input("workloadLink")]
        public Input<string>? WorkloadLink { get; set; }

        public DomainRouteState()
        {
        }
        public static new DomainRouteState Empty => new DomainRouteState();
    }
}
