# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetHelmTemplateResult',
    'AwaitableGetHelmTemplateResult',
    'get_helm_template',
    'get_helm_template_output',
]

@pulumi.output_type
class GetHelmTemplateResult:
    """
    A collection of values returned by getHelmTemplate.
    """
    def __init__(__self__, chart=None, dependency_update=None, description=None, gvc=None, id=None, insecure_skip_tls_verify=None, manifest=None, name=None, postrender=None, render_subchart_notes=None, repository=None, repository_ca_file=None, repository_cert_file=None, repository_key_file=None, repository_password=None, repository_username=None, set=None, set_file=None, set_string=None, values=None, verify=None, version=None):
        if chart and not isinstance(chart, str):
            raise TypeError("Expected argument 'chart' to be a str")
        pulumi.set(__self__, "chart", chart)
        if dependency_update and not isinstance(dependency_update, bool):
            raise TypeError("Expected argument 'dependency_update' to be a bool")
        pulumi.set(__self__, "dependency_update", dependency_update)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if gvc and not isinstance(gvc, str):
            raise TypeError("Expected argument 'gvc' to be a str")
        pulumi.set(__self__, "gvc", gvc)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if insecure_skip_tls_verify and not isinstance(insecure_skip_tls_verify, bool):
            raise TypeError("Expected argument 'insecure_skip_tls_verify' to be a bool")
        pulumi.set(__self__, "insecure_skip_tls_verify", insecure_skip_tls_verify)
        if manifest and not isinstance(manifest, str):
            raise TypeError("Expected argument 'manifest' to be a str")
        pulumi.set(__self__, "manifest", manifest)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if postrender and not isinstance(postrender, dict):
            raise TypeError("Expected argument 'postrender' to be a dict")
        pulumi.set(__self__, "postrender", postrender)
        if render_subchart_notes and not isinstance(render_subchart_notes, bool):
            raise TypeError("Expected argument 'render_subchart_notes' to be a bool")
        pulumi.set(__self__, "render_subchart_notes", render_subchart_notes)
        if repository and not isinstance(repository, str):
            raise TypeError("Expected argument 'repository' to be a str")
        pulumi.set(__self__, "repository", repository)
        if repository_ca_file and not isinstance(repository_ca_file, str):
            raise TypeError("Expected argument 'repository_ca_file' to be a str")
        pulumi.set(__self__, "repository_ca_file", repository_ca_file)
        if repository_cert_file and not isinstance(repository_cert_file, str):
            raise TypeError("Expected argument 'repository_cert_file' to be a str")
        pulumi.set(__self__, "repository_cert_file", repository_cert_file)
        if repository_key_file and not isinstance(repository_key_file, str):
            raise TypeError("Expected argument 'repository_key_file' to be a str")
        pulumi.set(__self__, "repository_key_file", repository_key_file)
        if repository_password and not isinstance(repository_password, str):
            raise TypeError("Expected argument 'repository_password' to be a str")
        pulumi.set(__self__, "repository_password", repository_password)
        if repository_username and not isinstance(repository_username, str):
            raise TypeError("Expected argument 'repository_username' to be a str")
        pulumi.set(__self__, "repository_username", repository_username)
        if set and not isinstance(set, dict):
            raise TypeError("Expected argument 'set' to be a dict")
        pulumi.set(__self__, "set", set)
        if set_file and not isinstance(set_file, dict):
            raise TypeError("Expected argument 'set_file' to be a dict")
        pulumi.set(__self__, "set_file", set_file)
        if set_string and not isinstance(set_string, dict):
            raise TypeError("Expected argument 'set_string' to be a dict")
        pulumi.set(__self__, "set_string", set_string)
        if values and not isinstance(values, list):
            raise TypeError("Expected argument 'values' to be a list")
        pulumi.set(__self__, "values", values)
        if verify and not isinstance(verify, bool):
            raise TypeError("Expected argument 'verify' to be a bool")
        pulumi.set(__self__, "verify", verify)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def chart(self) -> _builtins.str:
        return pulumi.get(self, "chart")

    @_builtins.property
    @pulumi.getter(name="dependencyUpdate")
    def dependency_update(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "dependency_update")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def gvc(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "gvc")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="insecureSkipTlsVerify")
    def insecure_skip_tls_verify(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "insecure_skip_tls_verify")

    @_builtins.property
    @pulumi.getter
    def manifest(self) -> _builtins.str:
        return pulumi.get(self, "manifest")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def postrender(self) -> Optional['outputs.GetHelmTemplatePostrenderResult']:
        return pulumi.get(self, "postrender")

    @_builtins.property
    @pulumi.getter(name="renderSubchartNotes")
    def render_subchart_notes(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "render_subchart_notes")

    @_builtins.property
    @pulumi.getter
    def repository(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "repository")

    @_builtins.property
    @pulumi.getter(name="repositoryCaFile")
    def repository_ca_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "repository_ca_file")

    @_builtins.property
    @pulumi.getter(name="repositoryCertFile")
    def repository_cert_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "repository_cert_file")

    @_builtins.property
    @pulumi.getter(name="repositoryKeyFile")
    def repository_key_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "repository_key_file")

    @_builtins.property
    @pulumi.getter(name="repositoryPassword")
    def repository_password(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "repository_password")

    @_builtins.property
    @pulumi.getter(name="repositoryUsername")
    def repository_username(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "repository_username")

    @_builtins.property
    @pulumi.getter
    def set(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "set")

    @_builtins.property
    @pulumi.getter(name="setFile")
    def set_file(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "set_file")

    @_builtins.property
    @pulumi.getter(name="setString")
    def set_string(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "set_string")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "values")

    @_builtins.property
    @pulumi.getter
    def verify(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "verify")

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "version")


class AwaitableGetHelmTemplateResult(GetHelmTemplateResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetHelmTemplateResult(
            chart=self.chart,
            dependency_update=self.dependency_update,
            description=self.description,
            gvc=self.gvc,
            id=self.id,
            insecure_skip_tls_verify=self.insecure_skip_tls_verify,
            manifest=self.manifest,
            name=self.name,
            postrender=self.postrender,
            render_subchart_notes=self.render_subchart_notes,
            repository=self.repository,
            repository_ca_file=self.repository_ca_file,
            repository_cert_file=self.repository_cert_file,
            repository_key_file=self.repository_key_file,
            repository_password=self.repository_password,
            repository_username=self.repository_username,
            set=self.set,
            set_file=self.set_file,
            set_string=self.set_string,
            values=self.values,
            verify=self.verify,
            version=self.version)


def get_helm_template(chart: Optional[_builtins.str] = None,
                      dependency_update: Optional[_builtins.bool] = None,
                      description: Optional[_builtins.str] = None,
                      gvc: Optional[_builtins.str] = None,
                      insecure_skip_tls_verify: Optional[_builtins.bool] = None,
                      name: Optional[_builtins.str] = None,
                      postrender: Optional[Union['GetHelmTemplatePostrenderArgs', 'GetHelmTemplatePostrenderArgsDict']] = None,
                      render_subchart_notes: Optional[_builtins.bool] = None,
                      repository: Optional[_builtins.str] = None,
                      repository_ca_file: Optional[_builtins.str] = None,
                      repository_cert_file: Optional[_builtins.str] = None,
                      repository_key_file: Optional[_builtins.str] = None,
                      repository_password: Optional[_builtins.str] = None,
                      repository_username: Optional[_builtins.str] = None,
                      set: Optional[Mapping[str, _builtins.str]] = None,
                      set_file: Optional[Mapping[str, _builtins.str]] = None,
                      set_string: Optional[Mapping[str, _builtins.str]] = None,
                      values: Optional[Sequence[_builtins.str]] = None,
                      verify: Optional[_builtins.bool] = None,
                      version: Optional[_builtins.str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetHelmTemplateResult:
    """
    Renders Helm chart templates using the `cpln helm template` command without installing. Useful for previewing rendered manifests or feeding them into other resources.

    For more information about cpln helm, see the [Control Plane Helm Guide](https://docs.controlplane.com/guides/cpln-helm).

    > **Important** The `cpln` CLI and `helm` CLI must both be installed and available in the PATH for this data source to function.

    ## Declaration

    ### Required

    - **name** (String) The release name to use for rendering the templates.
    - **chart** (String) Path to the chart. This can be a local path to a chart directory or packaged chart, or a chart name when used with `repository`.

    ### Optional

    - **gvc** (String) The GVC (Global Virtual Cloud) context for rendering the helm chart templates. Required only if the chart contains GVC-scoped resources and the GVC is not defined within the chart manifests.
    - **repository** (String) Chart repository URL where to locate the requested chart. Can be a Helm repository URL or an OCI registry URL.
    - **version** (String) Specify a version constraint for the chart version to use. This can be a specific tag (e.g., 1.1.1) or a valid range (e.g., ^2.0.0). If not specified, the latest version is used.
    - **values** (List of String) List of values in raw YAML to pass to the helm chart. Each entry is equivalent to a separate `--values/-f` flag. Values are merged in order, with later entries taking precedence.
    - **set** (Map of String) Set values on the command line. Map of key-value pairs. Equivalent to using `--set` flag.
    - **set_string** (Map of String) Set STRING values on the command line. Map of key-value pairs. Equivalent to using `--set-string` flag.
    - **set_file** (Map of String) Set values from files specified via the command line. Map of key to file path. Equivalent to using `--set-file` flag.
    - **dependency_update** (Boolean) Update dependencies if they are missing before rendering the chart.
    - **description** (String) Add a custom description.
    - **verify** (Boolean) Verify the package before using it.
    - **repository_username** (String) Chart repository username where to locate the requested chart.
    - **repository_password** (String, Sensitive) Chart repository password where to locate the requested chart.
    - **repository_ca_file** (String) Verify certificates of HTTPS-enabled servers using this CA bundle.
    - **repository_cert_file** (String) Identify HTTPS client using this SSL certificate file.
    - **repository_key_file** (String) Identify HTTPS client using this SSL key file.
    - **insecure_skip_tls_verify** (Boolean) Skip TLS certificate checks for the chart download.
    - **render_subchart_notes** (Boolean) If set, render subchart notes along with the parent.
    - **postrender** (Block) Post-renderer configuration:
      - **binary_path** (String, Required) The path to an executable to be used for post rendering.
      - **args** (List of String, Optional) Arguments to the post-renderer.

    ## Outputs

    The following attributes are exported:

    - **id** (String) The unique identifier for this data source (same as name).
    - **manifest** (String) The rendered manifest output from helm template.

    ## Example Usage
    """
    __args__ = dict()
    __args__['chart'] = chart
    __args__['dependencyUpdate'] = dependency_update
    __args__['description'] = description
    __args__['gvc'] = gvc
    __args__['insecureSkipTlsVerify'] = insecure_skip_tls_verify
    __args__['name'] = name
    __args__['postrender'] = postrender
    __args__['renderSubchartNotes'] = render_subchart_notes
    __args__['repository'] = repository
    __args__['repositoryCaFile'] = repository_ca_file
    __args__['repositoryCertFile'] = repository_cert_file
    __args__['repositoryKeyFile'] = repository_key_file
    __args__['repositoryPassword'] = repository_password
    __args__['repositoryUsername'] = repository_username
    __args__['set'] = set
    __args__['setFile'] = set_file
    __args__['setString'] = set_string
    __args__['values'] = values
    __args__['verify'] = verify
    __args__['version'] = version
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cpln:index/getHelmTemplate:getHelmTemplate', __args__, opts=opts, typ=GetHelmTemplateResult).value

    return AwaitableGetHelmTemplateResult(
        chart=pulumi.get(__ret__, 'chart'),
        dependency_update=pulumi.get(__ret__, 'dependency_update'),
        description=pulumi.get(__ret__, 'description'),
        gvc=pulumi.get(__ret__, 'gvc'),
        id=pulumi.get(__ret__, 'id'),
        insecure_skip_tls_verify=pulumi.get(__ret__, 'insecure_skip_tls_verify'),
        manifest=pulumi.get(__ret__, 'manifest'),
        name=pulumi.get(__ret__, 'name'),
        postrender=pulumi.get(__ret__, 'postrender'),
        render_subchart_notes=pulumi.get(__ret__, 'render_subchart_notes'),
        repository=pulumi.get(__ret__, 'repository'),
        repository_ca_file=pulumi.get(__ret__, 'repository_ca_file'),
        repository_cert_file=pulumi.get(__ret__, 'repository_cert_file'),
        repository_key_file=pulumi.get(__ret__, 'repository_key_file'),
        repository_password=pulumi.get(__ret__, 'repository_password'),
        repository_username=pulumi.get(__ret__, 'repository_username'),
        set=pulumi.get(__ret__, 'set'),
        set_file=pulumi.get(__ret__, 'set_file'),
        set_string=pulumi.get(__ret__, 'set_string'),
        values=pulumi.get(__ret__, 'values'),
        verify=pulumi.get(__ret__, 'verify'),
        version=pulumi.get(__ret__, 'version'))
def get_helm_template_output(chart: Optional[pulumi.Input[_builtins.str]] = None,
                             dependency_update: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                             description: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             gvc: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             insecure_skip_tls_verify: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                             name: Optional[pulumi.Input[_builtins.str]] = None,
                             postrender: Optional[pulumi.Input[Optional[Union['GetHelmTemplatePostrenderArgs', 'GetHelmTemplatePostrenderArgsDict']]]] = None,
                             render_subchart_notes: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                             repository: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             repository_ca_file: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             repository_cert_file: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             repository_key_file: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             repository_password: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             repository_username: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             set: Optional[pulumi.Input[Optional[Mapping[str, _builtins.str]]]] = None,
                             set_file: Optional[pulumi.Input[Optional[Mapping[str, _builtins.str]]]] = None,
                             set_string: Optional[pulumi.Input[Optional[Mapping[str, _builtins.str]]]] = None,
                             values: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                             verify: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                             version: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetHelmTemplateResult]:
    """
    Renders Helm chart templates using the `cpln helm template` command without installing. Useful for previewing rendered manifests or feeding them into other resources.

    For more information about cpln helm, see the [Control Plane Helm Guide](https://docs.controlplane.com/guides/cpln-helm).

    > **Important** The `cpln` CLI and `helm` CLI must both be installed and available in the PATH for this data source to function.

    ## Declaration

    ### Required

    - **name** (String) The release name to use for rendering the templates.
    - **chart** (String) Path to the chart. This can be a local path to a chart directory or packaged chart, or a chart name when used with `repository`.

    ### Optional

    - **gvc** (String) The GVC (Global Virtual Cloud) context for rendering the helm chart templates. Required only if the chart contains GVC-scoped resources and the GVC is not defined within the chart manifests.
    - **repository** (String) Chart repository URL where to locate the requested chart. Can be a Helm repository URL or an OCI registry URL.
    - **version** (String) Specify a version constraint for the chart version to use. This can be a specific tag (e.g., 1.1.1) or a valid range (e.g., ^2.0.0). If not specified, the latest version is used.
    - **values** (List of String) List of values in raw YAML to pass to the helm chart. Each entry is equivalent to a separate `--values/-f` flag. Values are merged in order, with later entries taking precedence.
    - **set** (Map of String) Set values on the command line. Map of key-value pairs. Equivalent to using `--set` flag.
    - **set_string** (Map of String) Set STRING values on the command line. Map of key-value pairs. Equivalent to using `--set-string` flag.
    - **set_file** (Map of String) Set values from files specified via the command line. Map of key to file path. Equivalent to using `--set-file` flag.
    - **dependency_update** (Boolean) Update dependencies if they are missing before rendering the chart.
    - **description** (String) Add a custom description.
    - **verify** (Boolean) Verify the package before using it.
    - **repository_username** (String) Chart repository username where to locate the requested chart.
    - **repository_password** (String, Sensitive) Chart repository password where to locate the requested chart.
    - **repository_ca_file** (String) Verify certificates of HTTPS-enabled servers using this CA bundle.
    - **repository_cert_file** (String) Identify HTTPS client using this SSL certificate file.
    - **repository_key_file** (String) Identify HTTPS client using this SSL key file.
    - **insecure_skip_tls_verify** (Boolean) Skip TLS certificate checks for the chart download.
    - **render_subchart_notes** (Boolean) If set, render subchart notes along with the parent.
    - **postrender** (Block) Post-renderer configuration:
      - **binary_path** (String, Required) The path to an executable to be used for post rendering.
      - **args** (List of String, Optional) Arguments to the post-renderer.

    ## Outputs

    The following attributes are exported:

    - **id** (String) The unique identifier for this data source (same as name).
    - **manifest** (String) The rendered manifest output from helm template.

    ## Example Usage
    """
    __args__ = dict()
    __args__['chart'] = chart
    __args__['dependencyUpdate'] = dependency_update
    __args__['description'] = description
    __args__['gvc'] = gvc
    __args__['insecureSkipTlsVerify'] = insecure_skip_tls_verify
    __args__['name'] = name
    __args__['postrender'] = postrender
    __args__['renderSubchartNotes'] = render_subchart_notes
    __args__['repository'] = repository
    __args__['repositoryCaFile'] = repository_ca_file
    __args__['repositoryCertFile'] = repository_cert_file
    __args__['repositoryKeyFile'] = repository_key_file
    __args__['repositoryPassword'] = repository_password
    __args__['repositoryUsername'] = repository_username
    __args__['set'] = set
    __args__['setFile'] = set_file
    __args__['setString'] = set_string
    __args__['values'] = values
    __args__['verify'] = verify
    __args__['version'] = version
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('cpln:index/getHelmTemplate:getHelmTemplate', __args__, opts=opts, typ=GetHelmTemplateResult)
    return __ret__.apply(lambda __response__: GetHelmTemplateResult(
        chart=pulumi.get(__response__, 'chart'),
        dependency_update=pulumi.get(__response__, 'dependency_update'),
        description=pulumi.get(__response__, 'description'),
        gvc=pulumi.get(__response__, 'gvc'),
        id=pulumi.get(__response__, 'id'),
        insecure_skip_tls_verify=pulumi.get(__response__, 'insecure_skip_tls_verify'),
        manifest=pulumi.get(__response__, 'manifest'),
        name=pulumi.get(__response__, 'name'),
        postrender=pulumi.get(__response__, 'postrender'),
        render_subchart_notes=pulumi.get(__response__, 'render_subchart_notes'),
        repository=pulumi.get(__response__, 'repository'),
        repository_ca_file=pulumi.get(__response__, 'repository_ca_file'),
        repository_cert_file=pulumi.get(__response__, 'repository_cert_file'),
        repository_key_file=pulumi.get(__response__, 'repository_key_file'),
        repository_password=pulumi.get(__response__, 'repository_password'),
        repository_username=pulumi.get(__response__, 'repository_username'),
        set=pulumi.get(__response__, 'set'),
        set_file=pulumi.get(__response__, 'set_file'),
        set_string=pulumi.get(__response__, 'set_string'),
        values=pulumi.get(__response__, 'values'),
        verify=pulumi.get(__response__, 'verify'),
        version=pulumi.get(__response__, 'version')))
