// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cpln

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"github.com/pulumiverse/pulumi-cpln/sdk/go/cpln/internal"
)

type VolumeSet struct {
	pulumi.CustomResourceState

	Autoscaling      VolumeSetAutoscalingPtrOutput `pulumi:"autoscaling"`
	CplnId           pulumi.StringOutput           `pulumi:"cplnId"`
	Description      pulumi.StringPtrOutput        `pulumi:"description"`
	FileSystemType   pulumi.StringPtrOutput        `pulumi:"fileSystemType"`
	Gvc              pulumi.StringOutput           `pulumi:"gvc"`
	InitialCapacity  pulumi.IntOutput              `pulumi:"initialCapacity"`
	Name             pulumi.StringOutput           `pulumi:"name"`
	PerformanceClass pulumi.StringOutput           `pulumi:"performanceClass"`
	SelfLink         pulumi.StringOutput           `pulumi:"selfLink"`
	Snapshots        VolumeSetSnapshotsPtrOutput   `pulumi:"snapshots"`
	Statuses         VolumeSetStatusArrayOutput    `pulumi:"statuses"`
	Tags             pulumi.StringMapOutput        `pulumi:"tags"`
}

// NewVolumeSet registers a new resource with the given unique name, arguments, and options.
func NewVolumeSet(ctx *pulumi.Context,
	name string, args *VolumeSetArgs, opts ...pulumi.ResourceOption) (*VolumeSet, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Gvc == nil {
		return nil, errors.New("invalid value for required argument 'Gvc'")
	}
	if args.InitialCapacity == nil {
		return nil, errors.New("invalid value for required argument 'InitialCapacity'")
	}
	if args.PerformanceClass == nil {
		return nil, errors.New("invalid value for required argument 'PerformanceClass'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VolumeSet
	err := ctx.RegisterResource("cpln:index/volumeSet:VolumeSet", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolumeSet gets an existing VolumeSet resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolumeSet(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumeSetState, opts ...pulumi.ResourceOption) (*VolumeSet, error) {
	var resource VolumeSet
	err := ctx.ReadResource("cpln:index/volumeSet:VolumeSet", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VolumeSet resources.
type volumeSetState struct {
	Autoscaling      *VolumeSetAutoscaling `pulumi:"autoscaling"`
	CplnId           *string               `pulumi:"cplnId"`
	Description      *string               `pulumi:"description"`
	FileSystemType   *string               `pulumi:"fileSystemType"`
	Gvc              *string               `pulumi:"gvc"`
	InitialCapacity  *int                  `pulumi:"initialCapacity"`
	Name             *string               `pulumi:"name"`
	PerformanceClass *string               `pulumi:"performanceClass"`
	SelfLink         *string               `pulumi:"selfLink"`
	Snapshots        *VolumeSetSnapshots   `pulumi:"snapshots"`
	Statuses         []VolumeSetStatus     `pulumi:"statuses"`
	Tags             map[string]string     `pulumi:"tags"`
}

type VolumeSetState struct {
	Autoscaling      VolumeSetAutoscalingPtrInput
	CplnId           pulumi.StringPtrInput
	Description      pulumi.StringPtrInput
	FileSystemType   pulumi.StringPtrInput
	Gvc              pulumi.StringPtrInput
	InitialCapacity  pulumi.IntPtrInput
	Name             pulumi.StringPtrInput
	PerformanceClass pulumi.StringPtrInput
	SelfLink         pulumi.StringPtrInput
	Snapshots        VolumeSetSnapshotsPtrInput
	Statuses         VolumeSetStatusArrayInput
	Tags             pulumi.StringMapInput
}

func (VolumeSetState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeSetState)(nil)).Elem()
}

type volumeSetArgs struct {
	Autoscaling      *VolumeSetAutoscaling `pulumi:"autoscaling"`
	Description      *string               `pulumi:"description"`
	FileSystemType   *string               `pulumi:"fileSystemType"`
	Gvc              string                `pulumi:"gvc"`
	InitialCapacity  int                   `pulumi:"initialCapacity"`
	Name             *string               `pulumi:"name"`
	PerformanceClass string                `pulumi:"performanceClass"`
	Snapshots        *VolumeSetSnapshots   `pulumi:"snapshots"`
	Tags             map[string]string     `pulumi:"tags"`
}

// The set of arguments for constructing a VolumeSet resource.
type VolumeSetArgs struct {
	Autoscaling      VolumeSetAutoscalingPtrInput
	Description      pulumi.StringPtrInput
	FileSystemType   pulumi.StringPtrInput
	Gvc              pulumi.StringInput
	InitialCapacity  pulumi.IntInput
	Name             pulumi.StringPtrInput
	PerformanceClass pulumi.StringInput
	Snapshots        VolumeSetSnapshotsPtrInput
	Tags             pulumi.StringMapInput
}

func (VolumeSetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeSetArgs)(nil)).Elem()
}

type VolumeSetInput interface {
	pulumi.Input

	ToVolumeSetOutput() VolumeSetOutput
	ToVolumeSetOutputWithContext(ctx context.Context) VolumeSetOutput
}

func (*VolumeSet) ElementType() reflect.Type {
	return reflect.TypeOf((**VolumeSet)(nil)).Elem()
}

func (i *VolumeSet) ToVolumeSetOutput() VolumeSetOutput {
	return i.ToVolumeSetOutputWithContext(context.Background())
}

func (i *VolumeSet) ToVolumeSetOutputWithContext(ctx context.Context) VolumeSetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeSetOutput)
}

func (i *VolumeSet) ToOutput(ctx context.Context) pulumix.Output[*VolumeSet] {
	return pulumix.Output[*VolumeSet]{
		OutputState: i.ToVolumeSetOutputWithContext(ctx).OutputState,
	}
}

// VolumeSetArrayInput is an input type that accepts VolumeSetArray and VolumeSetArrayOutput values.
// You can construct a concrete instance of `VolumeSetArrayInput` via:
//
//	VolumeSetArray{ VolumeSetArgs{...} }
type VolumeSetArrayInput interface {
	pulumi.Input

	ToVolumeSetArrayOutput() VolumeSetArrayOutput
	ToVolumeSetArrayOutputWithContext(context.Context) VolumeSetArrayOutput
}

type VolumeSetArray []VolumeSetInput

func (VolumeSetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VolumeSet)(nil)).Elem()
}

func (i VolumeSetArray) ToVolumeSetArrayOutput() VolumeSetArrayOutput {
	return i.ToVolumeSetArrayOutputWithContext(context.Background())
}

func (i VolumeSetArray) ToVolumeSetArrayOutputWithContext(ctx context.Context) VolumeSetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeSetArrayOutput)
}

func (i VolumeSetArray) ToOutput(ctx context.Context) pulumix.Output[[]*VolumeSet] {
	return pulumix.Output[[]*VolumeSet]{
		OutputState: i.ToVolumeSetArrayOutputWithContext(ctx).OutputState,
	}
}

// VolumeSetMapInput is an input type that accepts VolumeSetMap and VolumeSetMapOutput values.
// You can construct a concrete instance of `VolumeSetMapInput` via:
//
//	VolumeSetMap{ "key": VolumeSetArgs{...} }
type VolumeSetMapInput interface {
	pulumi.Input

	ToVolumeSetMapOutput() VolumeSetMapOutput
	ToVolumeSetMapOutputWithContext(context.Context) VolumeSetMapOutput
}

type VolumeSetMap map[string]VolumeSetInput

func (VolumeSetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VolumeSet)(nil)).Elem()
}

func (i VolumeSetMap) ToVolumeSetMapOutput() VolumeSetMapOutput {
	return i.ToVolumeSetMapOutputWithContext(context.Background())
}

func (i VolumeSetMap) ToVolumeSetMapOutputWithContext(ctx context.Context) VolumeSetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeSetMapOutput)
}

func (i VolumeSetMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*VolumeSet] {
	return pulumix.Output[map[string]*VolumeSet]{
		OutputState: i.ToVolumeSetMapOutputWithContext(ctx).OutputState,
	}
}

type VolumeSetOutput struct{ *pulumi.OutputState }

func (VolumeSetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VolumeSet)(nil)).Elem()
}

func (o VolumeSetOutput) ToVolumeSetOutput() VolumeSetOutput {
	return o
}

func (o VolumeSetOutput) ToVolumeSetOutputWithContext(ctx context.Context) VolumeSetOutput {
	return o
}

func (o VolumeSetOutput) ToOutput(ctx context.Context) pulumix.Output[*VolumeSet] {
	return pulumix.Output[*VolumeSet]{
		OutputState: o.OutputState,
	}
}

func (o VolumeSetOutput) Autoscaling() VolumeSetAutoscalingPtrOutput {
	return o.ApplyT(func(v *VolumeSet) VolumeSetAutoscalingPtrOutput { return v.Autoscaling }).(VolumeSetAutoscalingPtrOutput)
}

func (o VolumeSetOutput) CplnId() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringOutput { return v.CplnId }).(pulumi.StringOutput)
}

func (o VolumeSetOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o VolumeSetOutput) FileSystemType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringPtrOutput { return v.FileSystemType }).(pulumi.StringPtrOutput)
}

func (o VolumeSetOutput) Gvc() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringOutput { return v.Gvc }).(pulumi.StringOutput)
}

func (o VolumeSetOutput) InitialCapacity() pulumi.IntOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.IntOutput { return v.InitialCapacity }).(pulumi.IntOutput)
}

func (o VolumeSetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o VolumeSetOutput) PerformanceClass() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringOutput { return v.PerformanceClass }).(pulumi.StringOutput)
}

func (o VolumeSetOutput) SelfLink() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringOutput { return v.SelfLink }).(pulumi.StringOutput)
}

func (o VolumeSetOutput) Snapshots() VolumeSetSnapshotsPtrOutput {
	return o.ApplyT(func(v *VolumeSet) VolumeSetSnapshotsPtrOutput { return v.Snapshots }).(VolumeSetSnapshotsPtrOutput)
}

func (o VolumeSetOutput) Statuses() VolumeSetStatusArrayOutput {
	return o.ApplyT(func(v *VolumeSet) VolumeSetStatusArrayOutput { return v.Statuses }).(VolumeSetStatusArrayOutput)
}

func (o VolumeSetOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *VolumeSet) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

type VolumeSetArrayOutput struct{ *pulumi.OutputState }

func (VolumeSetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VolumeSet)(nil)).Elem()
}

func (o VolumeSetArrayOutput) ToVolumeSetArrayOutput() VolumeSetArrayOutput {
	return o
}

func (o VolumeSetArrayOutput) ToVolumeSetArrayOutputWithContext(ctx context.Context) VolumeSetArrayOutput {
	return o
}

func (o VolumeSetArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*VolumeSet] {
	return pulumix.Output[[]*VolumeSet]{
		OutputState: o.OutputState,
	}
}

func (o VolumeSetArrayOutput) Index(i pulumi.IntInput) VolumeSetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VolumeSet {
		return vs[0].([]*VolumeSet)[vs[1].(int)]
	}).(VolumeSetOutput)
}

type VolumeSetMapOutput struct{ *pulumi.OutputState }

func (VolumeSetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VolumeSet)(nil)).Elem()
}

func (o VolumeSetMapOutput) ToVolumeSetMapOutput() VolumeSetMapOutput {
	return o
}

func (o VolumeSetMapOutput) ToVolumeSetMapOutputWithContext(ctx context.Context) VolumeSetMapOutput {
	return o
}

func (o VolumeSetMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*VolumeSet] {
	return pulumix.Output[map[string]*VolumeSet]{
		OutputState: o.OutputState,
	}
}

func (o VolumeSetMapOutput) MapIndex(k pulumi.StringInput) VolumeSetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VolumeSet {
		return vs[0].(map[string]*VolumeSet)[vs[1].(string)]
	}).(VolumeSetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeSetInput)(nil)).Elem(), &VolumeSet{})
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeSetArrayInput)(nil)).Elem(), VolumeSetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeSetMapInput)(nil)).Elem(), VolumeSetMap{})
	pulumi.RegisterOutputType(VolumeSetOutput{})
	pulumi.RegisterOutputType(VolumeSetArrayOutput{})
	pulumi.RegisterOutputType(VolumeSetMapOutput{})
}
