// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class DomainStatusDnsConfig
    {
        /// <summary>
        /// The host in DNS terminology refers to the domain or subdomain that the DNS record is associated with. It's essentially the name that is being queried or managed. For example, in a DNS record for `www.example.com`, `Www` is a host in the domain `example.com`.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Time to live (TTL) is a value that signifies how long (in seconds) a DNS record should be cached by a resolver or a browser before a new request should be sent to refresh the data. Lower TTL values mean records are updated more frequently, which is beneficial for dynamic DNS configurations or during DNS migrations. Higher TTL values reduce the load on DNS servers and improve the speed of name resolution for end users by relying on cached data.
        /// </summary>
        public readonly int? Ttl;
        /// <summary>
        /// The DNS record type specifies the type of data the DNS record contains. Valid values: `CNAME`, `NS`, `TXT`.
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// The value of a DNS record contains the data the record is meant to convey, based on the type of the record.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private DomainStatusDnsConfig(
            string? host,

            int? ttl,

            string? type,

            string? value)
        {
            Host = host;
            Ttl = ttl;
            Type = type;
            Value = value;
        }
    }
}
