// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class DomainSpecPortRouteMirror
    {
        /// <summary>
        /// The percentage of traffic to mirror to the specified workload.
        /// </summary>
        public readonly double Percent;
        /// <summary>
        /// The workload to mirror traffic to.
        /// </summary>
        public readonly string WorkloadLink;

        [OutputConstructor]
        private DomainSpecPortRouteMirror(
            double percent,

            string workloadLink)
        {
            Percent = percent;
            WorkloadLink = workloadLink;
        }
    }
}
