// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class DomainSpecPort
    {
        /// <summary>
        /// A security feature implemented by web browsers to allow resources on a web page to be requested from another domain outside the domain from which the resource originated.
        /// </summary>
        public readonly Outputs.DomainSpecPortCors? Cors;
        /// <summary>
        /// Sets or overrides headers to all http requests for this route.
        /// </summary>
        public readonly int? Number;
        /// <summary>
        /// Allowed protocol. Valid values: `http`, `http2`, `tcp`. Default: `http2`.
        /// </summary>
        public readonly string? Protocol;
        /// <summary>
        /// Used for TLS connections for this Domain. End users are responsible for certificate updates.
        /// </summary>
        public readonly Outputs.DomainSpecPortTls? Tls;

        [OutputConstructor]
        private DomainSpecPort(
            Outputs.DomainSpecPortCors? cors,

            int? number,

            string? protocol,

            Outputs.DomainSpecPortTls? tls)
        {
            Cors = cors;
            Number = number;
            Protocol = protocol;
            Tls = tls;
        }
    }
}
