// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class DomainSpecPortCors
    {
        /// <summary>
        /// Determines whether the client-side code (typically running in a web browser) is allowed to include credentials (such as cookies, HTTP authentication, or client-side SSL certificates) in cross-origin requests.
        /// </summary>
        public readonly bool? AllowCredentials;
        /// <summary>
        /// Specifies the custom HTTP headers that are allowed in a cross-origin request to a specific resource.
        /// </summary>
        public readonly ImmutableArray<string> AllowHeaders;
        /// <summary>
        /// Specifies the HTTP methods (such as `GET`, `POST`, `PUT`, `DELETE`, etc.) that are allowed for a cross-origin request to a specific resource.
        /// </summary>
        public readonly ImmutableArray<string> AllowMethods;
        /// <summary>
        /// Determines which origins are allowed to access a particular resource on a server from a web browser.
        /// </summary>
        public readonly ImmutableArray<Outputs.DomainSpecPortCorsAllowOrigin> AllowOrigins;
        /// <summary>
        /// The HTTP headers that a server allows to be exposed to the client in response to a cross-origin request. These headers provide additional information about the server's capabilities or requirements, aiding in proper handling of the request by the client's browser or application.
        /// </summary>
        public readonly ImmutableArray<string> ExposeHeaders;
        /// <summary>
        /// Maximum amount of time that a preflight request result can be cached by the client browser. Input is expected as a duration string (i.e, 24h, 20m, etc.).
        /// </summary>
        public readonly string? MaxAge;

        [OutputConstructor]
        private DomainSpecPortCors(
            bool? allowCredentials,

            ImmutableArray<string> allowHeaders,

            ImmutableArray<string> allowMethods,

            ImmutableArray<Outputs.DomainSpecPortCorsAllowOrigin> allowOrigins,

            ImmutableArray<string> exposeHeaders,

            string? maxAge)
        {
            AllowCredentials = allowCredentials;
            AllowHeaders = allowHeaders;
            AllowMethods = allowMethods;
            AllowOrigins = allowOrigins;
            ExposeHeaders = exposeHeaders;
            MaxAge = maxAge;
        }
    }
}
