// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetGvcLoadBalancerRedirectResult
    {
        /// <summary>
        /// Specify the redirect url for all status codes in a class.
        /// </summary>
        public readonly Outputs.GetGvcLoadBalancerRedirectClassResult? Class;

        [OutputConstructor]
        private GetGvcLoadBalancerRedirectResult(Outputs.GetGvcLoadBalancerRedirectClassResult? @class)
        {
            Class = @class;
        }
    }
}
