// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetGvcLoadBalancerRedirectClassResult
    {
        /// <summary>
        /// An optional url redirect for 401 responses. Supports envoy format strings to include request information. E.g. https://your-oauth-server/oauth2/authorize?return_to=%REQ(:path)%&amp;client_id=your-client-id
        /// </summary>
        public readonly string? Status401;
        /// <summary>
        /// Specify the redirect url for any 500 level status code.
        /// </summary>
        public readonly string? Status5xx;

        [OutputConstructor]
        private GetGvcLoadBalancerRedirectClassResult(
            string? status401,

            string? status5xx)
        {
            Status401 = status401;
            Status5xx = status5xx;
        }
    }
}
