// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetImagesImageResult
    {
        public readonly string CplnId;
        public readonly string Digest;
        public readonly ImmutableArray<Outputs.GetImagesImageManifestResult> Manifests;
        public readonly string Name;
        public readonly string Repository;
        public readonly string SelfLink;
        public readonly string Tag;
        public readonly ImmutableDictionary<string, string> Tags;

        [OutputConstructor]
        private GetImagesImageResult(
            string cplnId,

            string digest,

            ImmutableArray<Outputs.GetImagesImageManifestResult> manifests,

            string name,

            string repository,

            string selfLink,

            string tag,

            ImmutableDictionary<string, string> tags)
        {
            CplnId = cplnId;
            Digest = digest;
            Manifests = manifests;
            Name = name;
            Repository = repository;
            SelfLink = selfLink;
            Tag = tag;
            Tags = tags;
        }
    }
}
