// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetSecretNatsAccountResult
    {
        /// <summary>
        /// Account ID.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// Private Key.
        /// </summary>
        public readonly string PrivateKey;

        [OutputConstructor]
        private GetSecretNatsAccountResult(
            string accountId,

            string privateKey)
        {
            AccountId = accountId;
            PrivateKey = privateKey;
        }
    }
}
