// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetWorkloadFirewallSpecResult
    {
        /// <summary>
        /// The external firewall is used to control inbound and outbound access to the workload for public-facing traffic.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetWorkloadFirewallSpecExternalResult> Externals;
        /// <summary>
        /// The internal firewall is used to control access between workloads.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetWorkloadFirewallSpecInternalResult> Internals;

        [OutputConstructor]
        private GetWorkloadFirewallSpecResult(
            ImmutableArray<Outputs.GetWorkloadFirewallSpecExternalResult> externals,

            ImmutableArray<Outputs.GetWorkloadFirewallSpecInternalResult> internals)
        {
            Externals = externals;
            Internals = internals;
        }
    }
}
