// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetWorkloadFirewallSpecInternalResult
    {
        /// <summary>
        /// Used to control the internal firewall configuration and mutual tls. Allowed Values: "none", "same-gvc", "same-org", "workload-list".
        /// </summary>
        public readonly string InboundAllowType;
        /// <summary>
        /// A list of specific workloads which are allowed to access this workload internally. This list is only used if the 'inboundAllowType' is set to 'workload-list'.
        /// </summary>
        public readonly ImmutableArray<string> InboundAllowWorkloads;

        [OutputConstructor]
        private GetWorkloadFirewallSpecInternalResult(
            string inboundAllowType,

            ImmutableArray<string> inboundAllowWorkloads)
        {
            InboundAllowType = inboundAllowType;
            InboundAllowWorkloads = inboundAllowWorkloads;
        }
    }
}
