// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GetWorkloadVmBootDiskSourceResult
    {
        /// <summary>
        /// Boot disk image fetched over HTTP/HTTPS.
        /// </summary>
        public readonly Outputs.GetWorkloadVmBootDiskSourceHttpResult Http;
        /// <summary>
        /// Boot from an OCI containerDisk image.
        /// </summary>
        public readonly Outputs.GetWorkloadVmBootDiskSourceOciResult Oci;

        [OutputConstructor]
        private GetWorkloadVmBootDiskSourceResult(
            Outputs.GetWorkloadVmBootDiskSourceHttpResult http,

            Outputs.GetWorkloadVmBootDiskSourceOciResult oci)
        {
            Http = http;
            Oci = oci;
        }
    }
}
