// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class GroupMemberQuery
    {
        /// <summary>
        /// Type of fetch. Specify either: `links` or `items`. Default: `items`.
        /// </summary>
        public readonly string? Fetch;
        public readonly Outputs.GroupMemberQuerySpec? Spec;

        [OutputConstructor]
        private GroupMemberQuery(
            string? fetch,

            Outputs.GroupMemberQuerySpec? spec)
        {
            Fetch = fetch;
            Spec = spec;
        }
    }
}
