// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class HelmReleasePostrender
    {
        /// <summary>
        /// Arguments to the post-renderer.
        /// </summary>
        public readonly ImmutableArray<string> Args;
        /// <summary>
        /// The path to an executable to be used for post rendering.
        /// </summary>
        public readonly string BinaryPath;

        [OutputConstructor]
        private HelmReleasePostrender(
            ImmutableArray<string> args,

            string binaryPath)
        {
            Args = args;
            BinaryPath = binaryPath;
        }
    }
}
