// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class IdentityAzureAccessPolicyRoleAssignment
    {
        public readonly bool? PlaceholderAttribute;
        /// <summary>
        /// List of assigned roles.
        /// </summary>
        public readonly ImmutableArray<string> Roles;
        /// <summary>
        /// Scope of roles.
        /// </summary>
        public readonly string? Scope;

        [OutputConstructor]
        private IdentityAzureAccessPolicyRoleAssignment(
            bool? placeholderAttribute,

            ImmutableArray<string> roles,

            string? scope)
        {
            PlaceholderAttribute = placeholderAttribute;
            Roles = roles;
            Scope = scope;
        }
    }
}
