// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class IdentityAwsAccessPolicy
    {
        /// <summary>
        /// Full link to referenced cloud account.
        /// </summary>
        public readonly string CloudAccountLink;
        /// <summary>
        /// List of policies.
        /// </summary>
        public readonly ImmutableArray<string> PolicyRefs;
        /// <summary>
        /// Role name.
        /// </summary>
        public readonly string? RoleName;
        /// <summary>
        /// The trust policy for the role.
        /// </summary>
        public readonly ImmutableArray<Outputs.IdentityAwsAccessPolicyTrustPolicy> TrustPolicies;

        [OutputConstructor]
        private IdentityAwsAccessPolicy(
            string cloudAccountLink,

            ImmutableArray<string> policyRefs,

            string? roleName,

            ImmutableArray<Outputs.IdentityAwsAccessPolicyTrustPolicy> trustPolicies)
        {
            CloudAccountLink = cloudAccountLink;
            PolicyRefs = policyRefs;
            RoleName = roleName;
            TrustPolicies = trustPolicies;
        }
    }
}
