// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class IdentityGcpAccessPolicyBinding
    {
        /// <summary>
        /// Name of resource for binding.
        /// </summary>
        public readonly string? Resource;
        /// <summary>
        /// List of allowed roles.
        /// </summary>
        public readonly ImmutableArray<string> Roles;

        [OutputConstructor]
        private IdentityGcpAccessPolicyBinding(
            string? resource,

            ImmutableArray<string> roles)
        {
            Resource = resource;
            Roles = roles;
        }
    }
}
