// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class IdentityNativeNetworkResource
    {
        public readonly Outputs.IdentityNativeNetworkResourceAwsPrivateLink? AwsPrivateLink;
        public readonly string Fqdn;
        public readonly Outputs.IdentityNativeNetworkResourceGcpServiceConnect? GcpServiceConnect;
        public readonly string Name;
        public readonly ImmutableArray<int> Ports;

        [OutputConstructor]
        private IdentityNativeNetworkResource(
            Outputs.IdentityNativeNetworkResourceAwsPrivateLink? awsPrivateLink,

            string fqdn,

            Outputs.IdentityNativeNetworkResourceGcpServiceConnect? gcpServiceConnect,

            string name,

            ImmutableArray<int> ports)
        {
            AwsPrivateLink = awsPrivateLink;
            Fqdn = fqdn;
            GcpServiceConnect = gcpServiceConnect;
            Name = name;
            Ports = ports;
        }
    }
}
