// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class IpSetStatusIpAddress
    {
        public readonly string? Created;
        public readonly string? Id;
        public readonly string? Ip;
        public readonly string? Name;
        public readonly string? State;

        [OutputConstructor]
        private IpSetStatusIpAddress(
            string? created,

            string? id,

            string? ip,

            string? name,

            string? state)
        {
            Created = created;
            Id = id;
            Ip = ip;
            Name = name;
            State = state;
        }
    }
}
