// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sLambdalabsProviderUnmanagedNodePool
    {
        /// <summary>
        /// Labels to attach to nodes of a node pool.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Labels;
        public readonly string Name;
        /// <summary>
        /// Taint for the nodes of a pool.
        /// </summary>
        public readonly ImmutableArray<Outputs.Mk8sLambdalabsProviderUnmanagedNodePoolTaint> Taints;

        [OutputConstructor]
        private Mk8sLambdalabsProviderUnmanagedNodePool(
            ImmutableDictionary<string, string>? labels,

            string name,

            ImmutableArray<Outputs.Mk8sLambdalabsProviderUnmanagedNodePoolTaint> taints)
        {
            Labels = labels;
            Name = name;
            Taints = taints;
        }
    }
}
