// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sPaperspaceProvider
    {
        public readonly Outputs.Mk8sPaperspaceProviderAutoscaler? Autoscaler;
        public readonly string NetworkId;
        public readonly ImmutableArray<Outputs.Mk8sPaperspaceProviderNodePool> NodePools;
        public readonly string? PreInstallScript;
        public readonly string Region;
        public readonly ImmutableArray<string> SharedDrives;
        public readonly string TokenSecretLink;
        public readonly ImmutableArray<Outputs.Mk8sPaperspaceProviderUnmanagedNodePool> UnmanagedNodePools;
        public readonly ImmutableArray<string> UserIds;

        [OutputConstructor]
        private Mk8sPaperspaceProvider(
            Outputs.Mk8sPaperspaceProviderAutoscaler? autoscaler,

            string networkId,

            ImmutableArray<Outputs.Mk8sPaperspaceProviderNodePool> nodePools,

            string? preInstallScript,

            string region,

            ImmutableArray<string> sharedDrives,

            string tokenSecretLink,

            ImmutableArray<Outputs.Mk8sPaperspaceProviderUnmanagedNodePool> unmanagedNodePools,

            ImmutableArray<string> userIds)
        {
            Autoscaler = autoscaler;
            NetworkId = networkId;
            NodePools = nodePools;
            PreInstallScript = preInstallScript;
            Region = region;
            SharedDrives = sharedDrives;
            TokenSecretLink = tokenSecretLink;
            UnmanagedNodePools = unmanagedNodePools;
            UserIds = userIds;
        }
    }
}
