// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sHetznerProviderDedicatedServerNodePoolTaint
    {
        public readonly string? Effect;
        public readonly string? Key;
        public readonly string? Value;

        [OutputConstructor]
        private Mk8sHetznerProviderDedicatedServerNodePoolTaint(
            string? effect,

            string? key,

            string? value)
        {
            Effect = effect;
            Key = key;
            Value = value;
        }
    }
}
