// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOnsByokConfigMiddlebox
    {
        /// <summary>
        /// Alert threshold, in Mbps, for middlebox bandwidth usage.
        /// </summary>
        public readonly int? BandwidthAlertMbps;
        /// <summary>
        /// Whether to deploy the middlebox component.
        /// </summary>
        public readonly bool? Enabled;

        [OutputConstructor]
        private Mk8sAddOnsByokConfigMiddlebox(
            int? bandwidthAlertMbps,

            bool? enabled)
        {
            BandwidthAlertMbps = bandwidthAlertMbps;
            Enabled = enabled;
        }
    }
}
