// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sStatusAddOnAwsWorkloadIdentity
    {
        public readonly ImmutableArray<Outputs.Mk8sStatusAddOnAwsWorkloadIdentityOidcProviderConfig> OidcProviderConfigs;
        public readonly string? TrustPolicy;

        [OutputConstructor]
        private Mk8sStatusAddOnAwsWorkloadIdentity(
            ImmutableArray<Outputs.Mk8sStatusAddOnAwsWorkloadIdentityOidcProviderConfig> oidcProviderConfigs,

            string? trustPolicy)
        {
            OidcProviderConfigs = oidcProviderConfigs;
            TrustPolicy = trustPolicy;
        }
    }
}
