// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOnsMetrics
    {
        public readonly bool? ApiServer;
        public readonly bool? Cadvisor;
        public readonly bool? CoreDns;
        public readonly bool? KubeState;
        public readonly bool? Kubelet;
        public readonly bool? NodeExporter;
        public readonly Outputs.Mk8sAddOnsMetricsScrapeAnnotated? ScrapeAnnotated;

        [OutputConstructor]
        private Mk8sAddOnsMetrics(
            bool? apiServer,

            bool? cadvisor,

            bool? coreDns,

            bool? kubeState,

            bool? kubelet,

            bool? nodeExporter,

            Outputs.Mk8sAddOnsMetricsScrapeAnnotated? scrapeAnnotated)
        {
            ApiServer = apiServer;
            Cadvisor = cadvisor;
            CoreDns = coreDns;
            KubeState = kubeState;
            Kubelet = kubelet;
            NodeExporter = nodeExporter;
            ScrapeAnnotated = scrapeAnnotated;
        }
    }
}
