// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sOblivusProviderUnmanagedNodePool
    {
        public readonly ImmutableDictionary<string, string>? Labels;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.Mk8sOblivusProviderUnmanagedNodePoolTaint> Taints;

        [OutputConstructor]
        private Mk8sOblivusProviderUnmanagedNodePool(
            ImmutableDictionary<string, string>? labels,

            string name,

            ImmutableArray<Outputs.Mk8sOblivusProviderUnmanagedNodePoolTaint> taints)
        {
            Labels = labels;
            Name = name;
            Taints = taints;
        }
    }
}
