// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOnsAwsEfs
    {
        /// <summary>
        /// Use this role for EFS interaction.
        /// </summary>
        public readonly string? RoleArn;

        [OutputConstructor]
        private Mk8sAddOnsAwsEfs(string? roleArn)
        {
            RoleArn = roleArn;
        }
    }
}
