// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOnsRegistryMirror
    {
        public readonly ImmutableArray<Outputs.Mk8sAddOnsRegistryMirrorMirror> Mirrors;

        [OutputConstructor]
        private Mk8sAddOnsRegistryMirror(ImmutableArray<Outputs.Mk8sAddOnsRegistryMirrorMirror> mirrors)
        {
            Mirrors = mirrors;
        }
    }
}
