// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOnsByokConfigMonitoringRemoteWriteAuthorization
    {
        /// <summary>
        /// Authorization credentials.
        /// </summary>
        public readonly string? Credentials;
        /// <summary>
        /// Path to a file containing the credentials.
        /// </summary>
        public readonly string? CredentialsFile;
        /// <summary>
        /// Authorization scheme (for example, "Bearer").
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private Mk8sAddOnsByokConfigMonitoringRemoteWriteAuthorization(
            string? credentials,

            string? credentialsFile,

            string? type)
        {
            Credentials = credentials;
            CredentialsFile = credentialsFile;
            Type = type;
        }
    }
}
