// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOns
    {
        public readonly Outputs.Mk8sAddOnsAwsEcr? AwsEcr;
        public readonly Outputs.Mk8sAddOnsAwsEfs? AwsEfs;
        public readonly Outputs.Mk8sAddOnsAwsElb? AwsElb;
        public readonly bool? AwsWorkloadIdentity;
        public readonly Outputs.Mk8sAddOnsAzureAcr? AzureAcr;
        public readonly Outputs.Mk8sAddOnsAzureWorkloadIdentity? AzureWorkloadIdentity;
        public readonly bool? Dashboard;
        public readonly bool? LocalPathStorage;
        public readonly Outputs.Mk8sAddOnsLogs? Logs;
        public readonly Outputs.Mk8sAddOnsMetrics? Metrics;
        public readonly Outputs.Mk8sAddOnsNvidia? Nvidia;

        [OutputConstructor]
        private Mk8sAddOns(
            Outputs.Mk8sAddOnsAwsEcr? awsEcr,

            Outputs.Mk8sAddOnsAwsEfs? awsEfs,

            Outputs.Mk8sAddOnsAwsElb? awsElb,

            bool? awsWorkloadIdentity,

            Outputs.Mk8sAddOnsAzureAcr? azureAcr,

            Outputs.Mk8sAddOnsAzureWorkloadIdentity? azureWorkloadIdentity,

            bool? dashboard,

            bool? localPathStorage,

            Outputs.Mk8sAddOnsLogs? logs,

            Outputs.Mk8sAddOnsMetrics? metrics,

            Outputs.Mk8sAddOnsNvidia? nvidia)
        {
            AwsEcr = awsEcr;
            AwsEfs = awsEfs;
            AwsElb = awsElb;
            AwsWorkloadIdentity = awsWorkloadIdentity;
            AzureAcr = azureAcr;
            AzureWorkloadIdentity = azureWorkloadIdentity;
            Dashboard = dashboard;
            LocalPathStorage = localPathStorage;
            Logs = logs;
            Metrics = metrics;
            Nvidia = nvidia;
        }
    }
}
