// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sAddOnsMetrics
    {
        /// <summary>
        /// Enable scraping apiserver stats.
        /// </summary>
        public readonly bool? ApiServer;
        /// <summary>
        /// Enable CNI-level container stats.
        /// </summary>
        public readonly bool? Cadvisor;
        /// <summary>
        /// Enable scraping of core-dns service.
        /// </summary>
        public readonly bool? CoreDns;
        /// <summary>
        /// Enable kube-state metrics.
        /// </summary>
        public readonly bool? KubeState;
        /// <summary>
        /// Enable scraping kubelet stats.
        /// </summary>
        public readonly bool? Kubelet;
        /// <summary>
        /// Enable collecting node-level stats (disk, network, filesystem, etc).
        /// </summary>
        public readonly bool? NodeExporter;
        public readonly bool? PlaceholderAttribute;
        /// <summary>
        /// Scrape pods annotated with prometheus.io/scrape=true.
        /// </summary>
        public readonly Outputs.Mk8sAddOnsMetricsScrapeAnnotated? ScrapeAnnotated;

        [OutputConstructor]
        private Mk8sAddOnsMetrics(
            bool? apiServer,

            bool? cadvisor,

            bool? coreDns,

            bool? kubeState,

            bool? kubelet,

            bool? nodeExporter,

            bool? placeholderAttribute,

            Outputs.Mk8sAddOnsMetricsScrapeAnnotated? scrapeAnnotated)
        {
            ApiServer = apiServer;
            Cadvisor = cadvisor;
            CoreDns = coreDns;
            KubeState = kubeState;
            Kubelet = kubelet;
            NodeExporter = nodeExporter;
            PlaceholderAttribute = placeholderAttribute;
            ScrapeAnnotated = scrapeAnnotated;
        }
    }
}
