// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class Mk8sTritonProviderLoadBalancerManual
    {
        public readonly string CnsInternalDomain;
        public readonly string CnsPublicDomain;
        public readonly int Count;
        public readonly string ImageId;
        /// <summary>
        /// Extra tags to attach to instances from a node pool.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Metadata;
        public readonly string PackageId;
        /// <summary>
        /// More private networks to join.
        /// </summary>
        public readonly ImmutableArray<string> PrivateNetworkIds;
        /// <summary>
        /// If set, machine will also get a public IP.
        /// </summary>
        public readonly string PublicNetworkId;
        /// <summary>
        /// Extra tags to attach to instances from a node pool.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Tags;

        [OutputConstructor]
        private Mk8sTritonProviderLoadBalancerManual(
            string cnsInternalDomain,

            string cnsPublicDomain,

            int count,

            string imageId,

            ImmutableDictionary<string, string>? metadata,

            string packageId,

            ImmutableArray<string> privateNetworkIds,

            string publicNetworkId,

            ImmutableDictionary<string, string>? tags)
        {
            CnsInternalDomain = cnsInternalDomain;
            CnsPublicDomain = cnsPublicDomain;
            Count = count;
            ImageId = imageId;
            Metadata = metadata;
            PackageId = packageId;
            PrivateNetworkIds = privateNetworkIds;
            PublicNetworkId = publicNetworkId;
            Tags = tags;
        }
    }
}
