// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class OrgLoggingSyslogLogging
    {
        /// <summary>
        /// Log Format. Valid values: RFC3164 or RFC5424.
        /// </summary>
        public readonly string? Format;
        /// <summary>
        /// Hostname of Syslog Endpoint.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Log Mode. Valid values: TCP, TLS, or UDP.
        /// </summary>
        public readonly string? Mode;
        /// <summary>
        /// Port of Syslog Endpoint.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Severity Level. See documentation for details. Valid values: 0 to 7.
        /// </summary>
        public readonly int? Severity;

        [OutputConstructor]
        private OrgLoggingSyslogLogging(
            string? format,

            string host,

            string? mode,

            int port,

            int? severity)
        {
            Format = format;
            Host = host;
            Mode = mode;
            Port = port;
            Severity = severity;
        }
    }
}
