// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class OrgLoggingDatadogLogging
    {
        public readonly string Credentials;
        public readonly string Host;

        [OutputConstructor]
        private OrgLoggingDatadogLogging(
            string credentials,

            string host)
        {
            Credentials = credentials;
            Host = host;
        }
    }
}
