// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class OrgLoggingStackdriverLogging
    {
        /// <summary>
        /// Full Link to a secret of type `Opaque`.
        /// </summary>
        public readonly string Credentials;
        /// <summary>
        /// A Google Cloud Provider region.
        /// </summary>
        public readonly string Location;

        [OutputConstructor]
        private OrgLoggingStackdriverLogging(
            string credentials,

            string location)
        {
            Credentials = credentials;
            Location = location;
        }
    }
}
