// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class OrgLoggingS3Logging
    {
        public readonly string Bucket;
        public readonly string Credentials;
        public readonly string? Prefix;
        public readonly string Region;

        [OutputConstructor]
        private OrgLoggingS3Logging(
            string bucket,

            string credentials,

            string? prefix,

            string region)
        {
            Bucket = bucket;
            Credentials = credentials;
            Prefix = prefix;
            Region = region;
        }
    }
}
