// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class SecretOpaque
    {
        /// <summary>
        /// Available encodings: `Plain`, `Base64`. Default: `Plain`.
        /// </summary>
        public readonly string? Encoding;
        /// <summary>
        /// Plain text or base64 encoded string. Use `Encoding` attribute to specify encoding.
        /// </summary>
        public readonly string Payload;

        [OutputConstructor]
        private SecretOpaque(
            string? encoding,

            string payload)
        {
            Encoding = encoding;
            Payload = payload;
        }
    }
}
