// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class VolumeSetStatus
    {
        /// <summary>
        /// Uniquely identifies the connection between the volume set and its workload. Every time a new connection is made, a new id is generated (e.g., If a workload is updated to remove the volume set, then updated again to reattach it, the volume set will have a new binding id).
        /// </summary>
        public readonly string? BindingId;
        /// <summary>
        /// Contains a list of actual volumes grouped by location.
        /// </summary>
        public readonly ImmutableArray<string> Locations;
        /// <summary>
        /// The GVC ID.
        /// </summary>
        public readonly string? ParentId;
        /// <summary>
        /// The url of the workload currently using this volume set (if any).
        /// </summary>
        public readonly string? UsedByWorkload;

        [OutputConstructor]
        private VolumeSetStatus(
            string? bindingId,

            ImmutableArray<string> locations,

            string? parentId,

            string? usedByWorkload)
        {
            BindingId = bindingId;
            Locations = locations;
            ParentId = parentId;
            UsedByWorkload = usedByWorkload;
        }
    }
}
