// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class WorkloadLocalOptionAutoscalingMulti
    {
        /// <summary>
        /// Valid values: `Cpu` or `Memory`.
        /// </summary>
        public readonly string? Metric;
        /// <summary>
        /// Control Plane will scale the number of replicas for this deployment up/down in order to be as close as possible to the target metric across all replicas of a deployment. Min: `1`. Max: `20000`.
        /// </summary>
        public readonly int? Target;

        [OutputConstructor]
        private WorkloadLocalOptionAutoscalingMulti(
            string? metric,

            int? target)
        {
            Metric = metric;
            Target = target;
        }
    }
}
