// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class WorkloadSecurityOptions
    {
        public readonly bool? _sentinel;
        public readonly int? FileSystemGroupId;

        [OutputConstructor]
        private WorkloadSecurityOptions(
            bool? _sentinel,

            int? fileSystemGroupId)
        {
            this._sentinel = _sentinel;
            FileSystemGroupId = fileSystemGroupId;
        }
    }
}
