// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class WorkloadStatusResolvedImage
    {
        /// <summary>
        /// A list of images that were resolved.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkloadStatusResolvedImageImage> Images;
        /// <summary>
        /// UTC Time when the images were resolved.
        /// </summary>
        public readonly string? ResolvedAt;
        /// <summary>
        /// Workload version the images were resolved for.
        /// </summary>
        public readonly int? ResolvedForVersion;

        [OutputConstructor]
        private WorkloadStatusResolvedImage(
            ImmutableArray<Outputs.WorkloadStatusResolvedImageImage> images,

            string? resolvedAt,

            int? resolvedForVersion)
        {
            Images = images;
            ResolvedAt = resolvedAt;
            ResolvedForVersion = resolvedForVersion;
        }
    }
}
