// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Outputs
{

    [OutputType]
    public sealed class WorkloadStatus
    {
        /// <summary>
        /// Canonical endpoint for the workload.
        /// </summary>
        public readonly string? CanonicalEndpoint;
        /// <summary>
        /// Current amount of replicas deployed.
        /// </summary>
        public readonly int? CurrentReplicaCount;
        /// <summary>
        /// Endpoint for the workload.
        /// </summary>
        public readonly string? Endpoint;
        /// <summary>
        /// Current health status.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkloadStatusHealthCheck> HealthChecks;
        /// <summary>
        /// Internal hostname for the workload. Used for service-to-service requests.
        /// </summary>
        public readonly string? InternalName;
        public readonly ImmutableArray<Outputs.WorkloadStatusLoadBalancer> LoadBalancers;
        /// <summary>
        /// ID of the parent object.
        /// </summary>
        public readonly string? ParentId;
        public readonly ImmutableArray<string> ReplicaInternalNames;
        /// <summary>
        /// Resolved images for workloads with dynamic tags enabled.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkloadStatusResolvedImage> ResolvedImages;

        [OutputConstructor]
        private WorkloadStatus(
            string? canonicalEndpoint,

            int? currentReplicaCount,

            string? endpoint,

            ImmutableArray<Outputs.WorkloadStatusHealthCheck> healthChecks,

            string? internalName,

            ImmutableArray<Outputs.WorkloadStatusLoadBalancer> loadBalancers,

            string? parentId,

            ImmutableArray<string> replicaInternalNames,

            ImmutableArray<Outputs.WorkloadStatusResolvedImage> resolvedImages)
        {
            CanonicalEndpoint = canonicalEndpoint;
            CurrentReplicaCount = currentReplicaCount;
            Endpoint = endpoint;
            HealthChecks = healthChecks;
            InternalName = internalName;
            LoadBalancers = loadBalancers;
            ParentId = parentId;
            ReplicaInternalNames = replicaInternalNames;
            ResolvedImages = resolvedImages;
        }
    }
}
