// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class CloudAccountAwsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Amazon Resource Name (ARN) Role.
        /// </summary>
        [Input("roleArn")]
        public Input<string>? RoleArn { get; set; }

        public CloudAccountAwsArgs()
        {
        }
        public static new CloudAccountAwsArgs Empty => new CloudAccountAwsArgs();
    }
}
