// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class DomainSpecPortRouteCanaryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The port to send canary traffic to. If not provided, the first configured port on the workload is used.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// The percentage of traffic to send to this canary workload. A weight of 0 disables the canary so it can be toggled on and off without removing it.
        /// </summary>
        [Input("weight", required: true)]
        public Input<int> Weight { get; set; } = null!;

        /// <summary>
        /// The canary workload to route a weighted percentage of traffic to.
        /// </summary>
        [Input("workloadLink", required: true)]
        public Input<string> WorkloadLink { get; set; } = null!;

        public DomainSpecPortRouteCanaryArgs()
        {
        }
        public static new DomainSpecPortRouteCanaryArgs Empty => new DomainSpecPortRouteCanaryArgs();
    }
}
