// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class DomainSpecPortCorsArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowCredentials")]
        public Input<bool>? AllowCredentials { get; set; }

        [Input("allowHeaders")]
        private InputList<string>? _allowHeaders;
        public InputList<string> AllowHeaders
        {
            get => _allowHeaders ?? (_allowHeaders = new InputList<string>());
            set => _allowHeaders = value;
        }

        [Input("allowMethods")]
        private InputList<string>? _allowMethods;
        public InputList<string> AllowMethods
        {
            get => _allowMethods ?? (_allowMethods = new InputList<string>());
            set => _allowMethods = value;
        }

        [Input("allowOrigins")]
        private InputList<Inputs.DomainSpecPortCorsAllowOriginArgs>? _allowOrigins;
        public InputList<Inputs.DomainSpecPortCorsAllowOriginArgs> AllowOrigins
        {
            get => _allowOrigins ?? (_allowOrigins = new InputList<Inputs.DomainSpecPortCorsAllowOriginArgs>());
            set => _allowOrigins = value;
        }

        [Input("exposeHeaders")]
        private InputList<string>? _exposeHeaders;
        public InputList<string> ExposeHeaders
        {
            get => _exposeHeaders ?? (_exposeHeaders = new InputList<string>());
            set => _exposeHeaders = value;
        }

        [Input("maxAge")]
        public Input<string>? MaxAge { get; set; }

        public DomainSpecPortCorsArgs()
        {
        }
        public static new DomainSpecPortCorsArgs Empty => new DomainSpecPortCorsArgs();
    }
}
