// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class DomainStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("dnsConfigs")]
        private InputList<Inputs.DomainStatusDnsConfigArgs>? _dnsConfigs;

        /// <summary>
        /// List of required DNS record entries.
        /// </summary>
        public InputList<Inputs.DomainStatusDnsConfigArgs> DnsConfigs
        {
            get => _dnsConfigs ?? (_dnsConfigs = new InputList<Inputs.DomainStatusDnsConfigArgs>());
            set => _dnsConfigs = value;
        }

        [Input("endpoints")]
        private InputList<Inputs.DomainStatusEndpointArgs>? _endpoints;

        /// <summary>
        /// List of configured domain endpoints.
        /// </summary>
        public InputList<Inputs.DomainStatusEndpointArgs> Endpoints
        {
            get => _endpoints ?? (_endpoints = new InputList<Inputs.DomainStatusEndpointArgs>());
            set => _endpoints = value;
        }

        [Input("fingerprint")]
        public Input<string>? Fingerprint { get; set; }

        [Input("locations")]
        private InputList<Inputs.DomainStatusLocationArgs>? _locations;

        /// <summary>
        /// Contains the cloud provider name, region, and certificate status.
        /// </summary>
        public InputList<Inputs.DomainStatusLocationArgs> Locations
        {
            get => _locations ?? (_locations = new InputList<Inputs.DomainStatusLocationArgs>());
            set => _locations = value;
        }

        /// <summary>
        /// Status of Domain. Possible values: `initializing`, `ready`, `pendingDnsConfig`, `pendingCertificate`, `usedByGvc`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Warning message.
        /// </summary>
        [Input("warning")]
        public Input<string>? Warning { get; set; }

        public DomainStatusArgs()
        {
        }
        public static new DomainStatusArgs Empty => new DomainStatusArgs();
    }
}
