// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetGvcOtelTracingArgs : global::Pulumi.InvokeArgs
    {
        [Input("customTags")]
        private Dictionary<string, string>? _customTags;

        /// <summary>
        /// Key-value map of custom tags.
        /// </summary>
        public Dictionary<string, string> CustomTags
        {
            get => _customTags ?? (_customTags = new Dictionary<string, string>());
            set => _customTags = value;
        }

        /// <summary>
        /// Tracing Endpoint Workload. Either the canonical endpoint or internal endpoint.
        /// </summary>
        [Input("endpoint", required: true)]
        public string Endpoint { get; set; } = null!;

        /// <summary>
        /// Determines what percentage of requests should be traced.
        /// </summary>
        [Input("sampling", required: true)]
        public double Sampling { get; set; }

        public GetGvcOtelTracingArgs()
        {
        }
        public static new GetGvcOtelTracingArgs Empty => new GetGvcOtelTracingArgs();
    }
}
