// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetGvcLocationQueryArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Type of fetch. Specify either: `Links` or `Items`. Default: `Items`.
        /// </summary>
        [Input("fetch", required: true)]
        public string Fetch { get; set; } = null!;

        [Input("specs")]
        private List<Inputs.GetGvcLocationQuerySpecArgs>? _specs;
        public List<Inputs.GetGvcLocationQuerySpecArgs> Specs
        {
            get => _specs ?? (_specs = new List<Inputs.GetGvcLocationQuerySpecArgs>());
            set => _specs = value;
        }

        public GetGvcLocationQueryArgs()
        {
        }
        public static new GetGvcLocationQueryArgs Empty => new GetGvcLocationQueryArgs();
    }
}
