// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetGvcLoadBalancerInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("dedicated")]
        public Input<bool>? Dedicated { get; set; }

        [Input("redirect")]
        public Input<Inputs.GetGvcLoadBalancerRedirectInputArgs>? Redirect { get; set; }

        [Input("trustedProxies")]
        public Input<int>? TrustedProxies { get; set; }

        public GetGvcLoadBalancerInputArgs()
        {
        }
        public static new GetGvcLoadBalancerInputArgs Empty => new GetGvcLoadBalancerInputArgs();
    }
}
