// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetGvcLocationQuerySpecTermInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type of query operation. Available values: `=`, `&gt;`, `&gt;=`, `&lt;`, `&lt;=`, `!=`, `~`, `=~`, `Exists`, `!exists`, `Contains`. Default: `=`.
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        /// <summary>
        /// Property to use for query evaluation.
        /// </summary>
        [Input("property", required: true)]
        public Input<string> Property { get; set; } = null!;

        /// <summary>
        /// Relation to use for query evaluation.
        /// </summary>
        [Input("rel", required: true)]
        public Input<string> Rel { get; set; } = null!;

        /// <summary>
        /// Tag key to use for query evaluation.
        /// </summary>
        [Input("tag", required: true)]
        public Input<string> Tag { get; set; } = null!;

        /// <summary>
        /// Testing value for query evaluation.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public GetGvcLocationQuerySpecTermInputArgs()
        {
        }
        public static new GetGvcLocationQuerySpecTermInputArgs Empty => new GetGvcLocationQuerySpecTermInputArgs();
    }
}
