// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetGvcLocationQuerySpecInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type of match. Available values: `All`, `Any`, `None`. Default: `All`.
        /// </summary>
        [Input("match", required: true)]
        public Input<string> Match { get; set; } = null!;

        [Input("terms")]
        private InputList<Inputs.GetGvcLocationQuerySpecTermInputArgs>? _terms;

        /// <summary>
        /// Terms can only contain one of the following attributes: `Property`, `Rel`, `Tag`.
        /// </summary>
        public InputList<Inputs.GetGvcLocationQuerySpecTermInputArgs> Terms
        {
            get => _terms ?? (_terms = new InputList<Inputs.GetGvcLocationQuerySpecTermInputArgs>());
            set => _terms = value;
        }

        public GetGvcLocationQuerySpecInputArgs()
        {
        }
        public static new GetGvcLocationQuerySpecInputArgs Empty => new GetGvcLocationQuerySpecInputArgs();
    }
}
