// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetOrgSecurityThreatDetectionInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates whether threat detection should be forwarded or not.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Any threats with this severity and more severe will be sent. Others will be ignored. Valid values: `Warning`, `Error`, or `Critical`.
        /// </summary>
        [Input("minimumSeverity")]
        public Input<string>? MinimumSeverity { get; set; }

        /// <summary>
        /// Configuration for syslog forwarding.
        /// </summary>
        [Input("syslog")]
        public Input<Inputs.GetOrgSecurityThreatDetectionSyslogInputArgs>? Syslog { get; set; }

        public GetOrgSecurityThreatDetectionInputArgs()
        {
        }
        public static new GetOrgSecurityThreatDetectionInputArgs Empty => new GetOrgSecurityThreatDetectionInputArgs();
    }
}
