// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetSecretKeypairArgs : global::Pulumi.InvokeArgs
    {
        [Input("passphrase")]
        private string? _passphrase;
        public string? Passphrase
        {
            get => _passphrase;
            set => _passphrase = value;
        }

        [Input("publicKey")]
        public string? PublicKey { get; set; }

        [Input("secretKey", required: true)]
        private string? _secretKey;
        public string? SecretKey
        {
            get => _secretKey;
            set => _secretKey = value;
        }

        public GetSecretKeypairArgs()
        {
        }
        public static new GetSecretKeypairArgs Empty => new GetSecretKeypairArgs();
    }
}
