// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadLocalOptionMultiZoneArgs : global::Pulumi.InvokeArgs
    {
        [Input("enabled", required: true)]
        public bool Enabled { get; set; }

        public GetWorkloadLocalOptionMultiZoneArgs()
        {
        }
        public static new GetWorkloadLocalOptionMultiZoneArgs Empty => new GetWorkloadLocalOptionMultiZoneArgs();
    }
}
