// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadOptionAutoscalingKedaArgs : global::Pulumi.InvokeArgs
    {
        [Input("advanceds")]
        private List<Inputs.GetWorkloadOptionAutoscalingKedaAdvancedArgs>? _advanceds;

        /// <summary>
        /// Advanced configuration options for KEDA.
        /// </summary>
        public List<Inputs.GetWorkloadOptionAutoscalingKedaAdvancedArgs> Advanceds
        {
            get => _advanceds ?? (_advanceds = new List<Inputs.GetWorkloadOptionAutoscalingKedaAdvancedArgs>());
            set => _advanceds = value;
        }

        /// <summary>
        /// The cooldown period in seconds after scaling down to 0 replicas before KEDA will allow scaling up again.
        /// </summary>
        [Input("cooldownPeriod", required: true)]
        public int CooldownPeriod { get; set; }

        [Input("fallbacks")]
        private List<Inputs.GetWorkloadOptionAutoscalingKedaFallbackArgs>? _fallbacks;

        /// <summary>
        /// Fallback configuration for KEDA.
        /// </summary>
        public List<Inputs.GetWorkloadOptionAutoscalingKedaFallbackArgs> Fallbacks
        {
            get => _fallbacks ?? (_fallbacks = new List<Inputs.GetWorkloadOptionAutoscalingKedaFallbackArgs>());
            set => _fallbacks = value;
        }

        /// <summary>
        /// The initial cooldown period in seconds after scaling down to 0 replicas before KEDA will allow scaling up again.
        /// </summary>
        [Input("initialCooldownPeriod", required: true)]
        public int InitialCooldownPeriod { get; set; }

        /// <summary>
        /// The interval in seconds at which KEDA will poll the external metrics to determine if scaling is required.
        /// </summary>
        [Input("pollingInterval", required: true)]
        public int PollingInterval { get; set; }

        [Input("triggers")]
        private List<Inputs.GetWorkloadOptionAutoscalingKedaTriggerArgs>? _triggers;

        /// <summary>
        /// An array of KEDA triggers to be used for scaling workloads in this GVC. This is used to define how KEDA will scale workloads in the GVC based on external metrics or events. Each trigger type may have its own specific configuration options.
        /// </summary>
        public List<Inputs.GetWorkloadOptionAutoscalingKedaTriggerArgs> Triggers
        {
            get => _triggers ?? (_triggers = new List<Inputs.GetWorkloadOptionAutoscalingKedaTriggerArgs>());
            set => _triggers = value;
        }

        public GetWorkloadOptionAutoscalingKedaArgs()
        {
        }
        public static new GetWorkloadOptionAutoscalingKedaArgs Empty => new GetWorkloadOptionAutoscalingKedaArgs();
    }
}
