// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadContainerLifecyclePreStopExecArgs : global::Pulumi.InvokeArgs
    {
        [Input("commands", required: true)]
        private List<string>? _commands;

        /// <summary>
        /// Command and arguments executed immediately before the container is stopped.
        /// </summary>
        public List<string> Commands
        {
            get => _commands ?? (_commands = new List<string>());
            set => _commands = value;
        }

        public GetWorkloadContainerLifecyclePreStopExecArgs()
        {
        }
        public static new GetWorkloadContainerLifecyclePreStopExecArgs Empty => new GetWorkloadContainerLifecyclePreStopExecArgs();
    }
}
