// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadContainerArgs : global::Pulumi.InvokeArgs
    {
        [Input("args", required: true)]
        private List<string>? _args;

        /// <summary>
        /// Command line arguments passed to the container at runtime. Replaces the CMD arguments of the running container. It is an ordered list.
        /// </summary>
        public List<string> Args
        {
            get => _args ?? (_args = new List<string>());
            set => _args = value;
        }

        /// <summary>
        /// Override the entry point.
        /// </summary>
        [Input("command", required: true)]
        public string Command { get; set; } = null!;

        /// <summary>
        /// Reserved CPU of the workload when capacityAI is disabled. Maximum CPU when CapacityAI is enabled. Default: "50m".
        /// </summary>
        [Input("cpu", required: true)]
        public string Cpu { get; set; } = null!;

        [Input("env", required: true)]
        private Dictionary<string, string>? _env;

        /// <summary>
        /// Name-Value list of environment variables.
        /// </summary>
        public Dictionary<string, string> Env
        {
            get => _env ?? (_env = new Dictionary<string, string>());
            set => _env = value;
        }

        [Input("gpuCustoms")]
        private List<Inputs.GetWorkloadContainerGpuCustomArgs>? _gpuCustoms;
        public List<Inputs.GetWorkloadContainerGpuCustomArgs> GpuCustoms
        {
            get => _gpuCustoms ?? (_gpuCustoms = new List<Inputs.GetWorkloadContainerGpuCustomArgs>());
            set => _gpuCustoms = value;
        }

        [Input("gpuNvidias")]
        private List<Inputs.GetWorkloadContainerGpuNvidiaArgs>? _gpuNvidias;

        /// <summary>
        /// GPUs manufactured by NVIDIA, which are specialized hardware accelerators used to offload and accelerate computationally intensive tasks within the workload.
        /// </summary>
        public List<Inputs.GetWorkloadContainerGpuNvidiaArgs> GpuNvidias
        {
            get => _gpuNvidias ?? (_gpuNvidias = new List<Inputs.GetWorkloadContainerGpuNvidiaArgs>());
            set => _gpuNvidias = value;
        }

        /// <summary>
        /// The full image and tag path.
        /// </summary>
        [Input("image", required: true)]
        public string Image { get; set; } = null!;

        /// <summary>
        /// Enables inheritance of GVC environment variables. A variable in spec.env will override a GVC variable with the same name.
        /// </summary>
        [Input("inheritEnv", required: true)]
        public bool InheritEnv { get; set; }

        [Input("lifecycles")]
        private List<Inputs.GetWorkloadContainerLifecycleArgs>? _lifecycles;

        /// <summary>
        /// Lifecycle [Reference Page](https://docs.controlplane.com/reference/workload#lifecycle).
        /// </summary>
        public List<Inputs.GetWorkloadContainerLifecycleArgs> Lifecycles
        {
            get => _lifecycles ?? (_lifecycles = new List<Inputs.GetWorkloadContainerLifecycleArgs>());
            set => _lifecycles = value;
        }

        [Input("livenessProbes")]
        private List<Inputs.GetWorkloadContainerLivenessProbeArgs>? _livenessProbes;

        /// <summary>
        /// Liveness Probe
        /// </summary>
        public List<Inputs.GetWorkloadContainerLivenessProbeArgs> LivenessProbes
        {
            get => _livenessProbes ?? (_livenessProbes = new List<Inputs.GetWorkloadContainerLivenessProbeArgs>());
            set => _livenessProbes = value;
        }

        /// <summary>
        /// Reserved memory of the workload when capacityAI is disabled. Maximum memory when CapacityAI is enabled. Default: "128Mi".
        /// </summary>
        [Input("memory", required: true)]
        public string Memory { get; set; } = null!;

        [Input("metrics")]
        private List<Inputs.GetWorkloadContainerMetricArgs>? _metrics;

        /// <summary>
        /// [Reference Page](https://docs.controlplane.com/reference/workload#metrics).
        /// </summary>
        public List<Inputs.GetWorkloadContainerMetricArgs> Metrics
        {
            get => _metrics ?? (_metrics = new List<Inputs.GetWorkloadContainerMetricArgs>());
            set => _metrics = value;
        }

        /// <summary>
        /// Minimum CPU when capacity AI is enabled.
        /// </summary>
        [Input("minCpu", required: true)]
        public string MinCpu { get; set; } = null!;

        /// <summary>
        /// Minimum memory when capacity AI is enabled.
        /// </summary>
        [Input("minMemory", required: true)]
        public string MinMemory { get; set; } = null!;

        /// <summary>
        /// Name of the container.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The port the container exposes. Only one container is allowed to specify a port. Min: `80`. Max: `65535`. Used by `Serverless` Workload type. **DEPRECATED - Use `Ports`.**
        /// </summary>
        [Input("port", required: true)]
        public int Port { get; set; }

        [Input("ports")]
        private List<Inputs.GetWorkloadContainerPortArgs>? _ports;

        /// <summary>
        /// Communication endpoints used by the workload to send and receive network traffic.
        /// </summary>
        public List<Inputs.GetWorkloadContainerPortArgs> Ports
        {
            get => _ports ?? (_ports = new List<Inputs.GetWorkloadContainerPortArgs>());
            set => _ports = value;
        }

        [Input("readinessProbes")]
        private List<Inputs.GetWorkloadContainerReadinessProbeArgs>? _readinessProbes;

        /// <summary>
        /// Readiness Probe
        /// </summary>
        public List<Inputs.GetWorkloadContainerReadinessProbeArgs> ReadinessProbes
        {
            get => _readinessProbes ?? (_readinessProbes = new List<Inputs.GetWorkloadContainerReadinessProbeArgs>());
            set => _readinessProbes = value;
        }

        [Input("volumes")]
        private List<Inputs.GetWorkloadContainerVolumeArgs>? _volumes;

        /// <summary>
        /// Mount Object Store (S3, GCS, AzureBlob) buckets as file system.
        /// </summary>
        public List<Inputs.GetWorkloadContainerVolumeArgs> Volumes
        {
            get => _volumes ?? (_volumes = new List<Inputs.GetWorkloadContainerVolumeArgs>());
            set => _volumes = value;
        }

        /// <summary>
        /// Override the working directory. Must be an absolute path.
        /// </summary>
        [Input("workingDirectory", required: true)]
        public string WorkingDirectory { get; set; } = null!;

        public GetWorkloadContainerArgs()
        {
        }
        public static new GetWorkloadContainerArgs Empty => new GetWorkloadContainerArgs();
    }
}
