// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadLoadBalancerDirectPortArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The port on the container tha will receive this traffic.
        /// </summary>
        [Input("containerPort", required: true)]
        public int ContainerPort { get; set; }

        /// <summary>
        /// The port that is available publicly.
        /// </summary>
        [Input("externalPort", required: true)]
        public int ExternalPort { get; set; }

        /// <summary>
        /// The protocol that is exposed publicly.
        /// </summary>
        [Input("protocol", required: true)]
        public string Protocol { get; set; } = null!;

        /// <summary>
        /// Overrides the default `Https` url scheme that will be used for links in the UI and status.
        /// </summary>
        [Input("scheme", required: true)]
        public string Scheme { get; set; } = null!;

        public GetWorkloadLoadBalancerDirectPortArgs()
        {
        }
        public static new GetWorkloadLoadBalancerDirectPortArgs Empty => new GetWorkloadLoadBalancerDirectPortArgs();
    }
}
