// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadLoadBalancerGeoLocationArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// When enabled, geo location headers will be included on inbound http requests. Existing headers will be replaced.
        /// </summary>
        [Input("enabled", required: true)]
        public bool Enabled { get; set; }

        [Input("headers")]
        private List<Inputs.GetWorkloadLoadBalancerGeoLocationHeaderArgs>? _headers;
        public List<Inputs.GetWorkloadLoadBalancerGeoLocationHeaderArgs> Headers
        {
            get => _headers ?? (_headers = new List<Inputs.GetWorkloadLoadBalancerGeoLocationHeaderArgs>());
            set => _headers = value;
        }

        public GetWorkloadLoadBalancerGeoLocationArgs()
        {
        }
        public static new GetWorkloadLoadBalancerGeoLocationArgs Empty => new GetWorkloadLoadBalancerGeoLocationArgs();
    }
}
