// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadContainerPortArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Port to expose.
        /// </summary>
        [Input("number", required: true)]
        public int Number { get; set; }

        /// <summary>
        /// Protocol. Choice of: `Http`, `Http2`, `Tcp`, or `Grpc`.
        /// </summary>
        [Input("protocol", required: true)]
        public string Protocol { get; set; } = null!;

        public GetWorkloadContainerPortArgs()
        {
        }
        public static new GetWorkloadContainerPortArgs Empty => new GetWorkloadContainerPortArgs();
    }
}
