// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GetWorkloadContainerMetricArgs : global::Pulumi.InvokeArgs
    {
        [Input("dropMetrics", required: true)]
        private List<string>? _dropMetrics;

        /// <summary>
        /// Drop metrics that match given patterns.
        /// </summary>
        public List<string> DropMetrics
        {
            get => _dropMetrics ?? (_dropMetrics = new List<string>());
            set => _dropMetrics = value;
        }

        /// <summary>
        /// Path from container emitting custom metrics.
        /// </summary>
        [Input("path", required: true)]
        public string Path { get; set; } = null!;

        /// <summary>
        /// Port from container emitting custom metrics.
        /// </summary>
        [Input("port", required: true)]
        public int Port { get; set; }

        public GetWorkloadContainerMetricArgs()
        {
        }
        public static new GetWorkloadContainerMetricArgs Empty => new GetWorkloadContainerMetricArgs();
    }
}
