// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class GroupIdentityMatcherArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Executes the expression against the users' claims to decide whether a user belongs to this group. This method is useful for managing the grouping of users logged in with SAML providers.
        /// </summary>
        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        /// <summary>
        /// Language of the expression. Either `Jmespath` or `Javascript`. Default: `Jmespath`.
        /// </summary>
        [Input("language")]
        public Input<string>? Language { get; set; }

        public GroupIdentityMatcherArgs()
        {
        }
        public static new GroupIdentityMatcherArgs Empty => new GroupIdentityMatcherArgs();
    }
}
