// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class IdentityAzureAccessPolicyRoleAssignmentGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("placeholderAttribute")]
        public Input<bool>? PlaceholderAttribute { get; set; }

        [Input("roles")]
        private InputList<string>? _roles;

        /// <summary>
        /// List of assigned roles.
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        /// <summary>
        /// Scope of roles.
        /// </summary>
        [Input("scope")]
        public Input<string>? Scope { get; set; }

        public IdentityAzureAccessPolicyRoleAssignmentGetArgs()
        {
        }
        public static new IdentityAzureAccessPolicyRoleAssignmentGetArgs Empty => new IdentityAzureAccessPolicyRoleAssignmentGetArgs();
    }
}
