// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsByokConfigLonghornGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Replica factor for Longhorn volumes. Minimum: 1.
        /// </summary>
        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        public Mk8sAddOnsByokConfigLonghornGetArgs()
        {
        }
        public static new Mk8sAddOnsByokConfigLonghornGetArgs Empty => new Mk8sAddOnsByokConfigLonghornGetArgs();
    }
}
