// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsByokConfigCommonPdbGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Maximum number of pods that can be unavailable during disruptions.
        /// </summary>
        [Input("maxUnavailable")]
        public Input<int>? MaxUnavailable { get; set; }

        public Mk8sAddOnsByokConfigCommonPdbGetArgs()
        {
        }
        public static new Mk8sAddOnsByokConfigCommonPdbGetArgs Empty => new Mk8sAddOnsByokConfigCommonPdbGetArgs();
    }
}
