// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsAzureWorkloadIdentityGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Tenant ID to use for workload identity.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        public Mk8sAddOnsAzureWorkloadIdentityGetArgs()
        {
        }
        public static new Mk8sAddOnsAzureWorkloadIdentityGetArgs Empty => new Mk8sAddOnsAzureWorkloadIdentityGetArgs();
    }
}
