// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsNvidiaArgs : global::Pulumi.ResourceArgs
    {
        [Input("taintGpuNodes")]
        public Input<bool>? TaintGpuNodes { get; set; }

        public Mk8sAddOnsNvidiaArgs()
        {
        }
        public static new Mk8sAddOnsNvidiaArgs Empty => new Mk8sAddOnsNvidiaArgs();
    }
}
