// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsByokConfigMonitoringGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kube-state-metrics resource overrides.
        /// </summary>
        [Input("kubeStateMetrics")]
        public Input<Inputs.Mk8sAddOnsByokConfigMonitoringKubeStateMetricsGetArgs>? KubeStateMetrics { get; set; }

        /// <summary>
        /// Maximum memory limit for monitoring components.
        /// </summary>
        [Input("maxMemory")]
        public Input<string>? MaxMemory { get; set; }

        /// <summary>
        /// Minimum memory request for monitoring components.
        /// </summary>
        [Input("minMemory")]
        public Input<string>? MinMemory { get; set; }

        /// <summary>
        /// Prometheus deployment configuration.
        /// </summary>
        [Input("prometheus")]
        public Input<Inputs.Mk8sAddOnsByokConfigMonitoringPrometheusGetArgs>? Prometheus { get; set; }

        public Mk8sAddOnsByokConfigMonitoringGetArgs()
        {
        }
        public static new Mk8sAddOnsByokConfigMonitoringGetArgs Empty => new Mk8sAddOnsByokConfigMonitoringGetArgs();
    }
}
