// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sTritonProviderLoadBalancerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("gateway")]
        public Input<Inputs.Mk8sTritonProviderLoadBalancerGatewayGetArgs>? Gateway { get; set; }

        [Input("manual")]
        public Input<Inputs.Mk8sTritonProviderLoadBalancerManualGetArgs>? Manual { get; set; }

        public Mk8sTritonProviderLoadBalancerGetArgs()
        {
        }
        public static new Mk8sTritonProviderLoadBalancerGetArgs Empty => new Mk8sTritonProviderLoadBalancerGetArgs();
    }
}
