// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsByokConfigByokGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// When set, the BYOK installation does not provision any default storage classes.
        /// </summary>
        [Input("noDefaultStorageClasses")]
        public Input<bool>? NoDefaultStorageClasses { get; set; }

        public Mk8sAddOnsByokConfigByokGetArgs()
        {
        }
        public static new Mk8sAddOnsByokConfigByokGetArgs Empty => new Mk8sAddOnsByokConfigByokGetArgs();
    }
}
