// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsLogsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Collect k8s audit log as log events.
        /// </summary>
        [Input("auditEnabled")]
        public Input<bool>? AuditEnabled { get; set; }

        /// <summary>
        /// Collect docker logs if docker is also running.
        /// </summary>
        [Input("docker")]
        public Input<bool>? Docker { get; set; }

        /// <summary>
        /// Collect K8S events from all namespaces.
        /// </summary>
        [Input("events")]
        public Input<bool>? Events { get; set; }

        [Input("excludeNamespaces")]
        public Input<string>? ExcludeNamespaces { get; set; }

        [Input("includeNamespaces")]
        public Input<string>? IncludeNamespaces { get; set; }

        /// <summary>
        /// Collect kernel logs.
        /// </summary>
        [Input("kernel")]
        public Input<bool>? Kernel { get; set; }

        /// <summary>
        /// Collect kubelet logs from journald.
        /// </summary>
        [Input("kubelet")]
        public Input<bool>? Kubelet { get; set; }

        public Mk8sAddOnsLogsGetArgs()
        {
        }
        public static new Mk8sAddOnsLogsGetArgs Empty => new Mk8sAddOnsLogsGetArgs();
    }
}
