// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsAwsEfsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Use this role for EFS interaction.
        /// </summary>
        [Input("roleArn")]
        public Input<string>? RoleArn { get; set; }

        public Mk8sAddOnsAwsEfsGetArgs()
        {
        }
        public static new Mk8sAddOnsAwsEfsGetArgs Empty => new Mk8sAddOnsAwsEfsGetArgs();
    }
}
