// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsKubevirtArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Filesystem-mode StorageClass CDI uses for import scratch space. Required when the cluster default StorageClass is block-mode.
        /// </summary>
        [Input("scratchSpaceStorageClass")]
        public Input<string>? ScratchSpaceStorageClass { get; set; }

        public Mk8sAddOnsKubevirtArgs()
        {
        }
        public static new Mk8sAddOnsKubevirtArgs Empty => new Mk8sAddOnsKubevirtArgs();
    }
}
