// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsRegistryMirrorMirrorArgs : global::Pulumi.ResourceArgs
    {
        [Input("mirrors")]
        private InputList<string>? _mirrors;
        public InputList<string> Mirrors
        {
            get => _mirrors ?? (_mirrors = new InputList<string>());
            set => _mirrors = value;
        }

        [Input("registry", required: true)]
        public Input<string> Registry { get; set; } = null!;

        public Mk8sAddOnsRegistryMirrorMirrorArgs()
        {
        }
        public static new Mk8sAddOnsRegistryMirrorMirrorArgs Empty => new Mk8sAddOnsRegistryMirrorMirrorArgs();
    }
}
