// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sStatusAddOnLogGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Loki endpoint to query logs from.
        /// </summary>
        [Input("lokiAddress")]
        public Input<string>? LokiAddress { get; set; }

        public Mk8sStatusAddOnLogGetArgs()
        {
        }
        public static new Mk8sStatusAddOnLogGetArgs Empty => new Mk8sStatusAddOnLogGetArgs();
    }
}
