// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsByokConfigIstioIstiodArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CPU limit applied to istiod pods.
        /// </summary>
        [Input("maxCpu")]
        public Input<string>? MaxCpu { get; set; }

        /// <summary>
        /// Memory limit applied to istiod pods.
        /// </summary>
        [Input("maxMemory")]
        public Input<string>? MaxMemory { get; set; }

        /// <summary>
        /// CPU request applied to istiod pods.
        /// </summary>
        [Input("minCpu")]
        public Input<string>? MinCpu { get; set; }

        /// <summary>
        /// Memory request applied to istiod pods.
        /// </summary>
        [Input("minMemory")]
        public Input<string>? MinMemory { get; set; }

        /// <summary>
        /// Pod disruption budget maxUnavailable for istiod.
        /// </summary>
        [Input("pdb")]
        public Input<int>? Pdb { get; set; }

        /// <summary>
        /// Number of istiod replicas.
        /// </summary>
        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        public Mk8sAddOnsByokConfigIstioIstiodArgs()
        {
        }
        public static new Mk8sAddOnsByokConfigIstioIstiodArgs Empty => new Mk8sAddOnsByokConfigIstioIstiodArgs();
    }
}
