// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAwsProviderNodePoolCpuOptionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable nested virtualization. Only supported on 8th generation Intel instance types (c8i, m8i, r8i and variants).
        /// </summary>
        [Input("nestedVirtualization")]
        public Input<bool>? NestedVirtualization { get; set; }

        public Mk8sAwsProviderNodePoolCpuOptionsArgs()
        {
        }
        public static new Mk8sAwsProviderNodePoolCpuOptionsArgs Empty => new Mk8sAwsProviderNodePoolCpuOptionsArgs();
    }
}
