// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sGcpProviderGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("autoscaler")]
        public Input<Inputs.Mk8sGcpProviderAutoscalerGetArgs>? Autoscaler { get; set; }

        /// <summary>
        /// Default image for all nodes.
        /// </summary>
        [Input("image", required: true)]
        public Input<Inputs.Mk8sGcpProviderImageGetArgs> Image { get; set; } = null!;

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Extra tags to attach to all created objects.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("metadata")]
        private InputMap<string>? _metadata;
        public InputMap<string> Metadata
        {
            get => _metadata ?? (_metadata = new InputMap<string>());
            set => _metadata = value;
        }

        /// <summary>
        /// VPC network used by the cluster.
        /// </summary>
        [Input("network", required: true)]
        public Input<string> Network { get; set; } = null!;

        [Input("networking", required: true)]
        public Input<Inputs.Mk8sGcpProviderNetworkingGetArgs> Networking { get; set; } = null!;

        [Input("nodePools")]
        private InputList<Inputs.Mk8sGcpProviderNodePoolGetArgs>? _nodePools;
        public InputList<Inputs.Mk8sGcpProviderNodePoolGetArgs> NodePools
        {
            get => _nodePools ?? (_nodePools = new InputList<Inputs.Mk8sGcpProviderNodePoolGetArgs>());
            set => _nodePools = value;
        }

        /// <summary>
        /// Optional shell script that will be run before K8s is installed. Supports SSM.
        /// </summary>
        [Input("preInstallScript")]
        public Input<string>? PreInstallScript { get; set; }

        /// <summary>
        /// GCP project ID that hosts the cluster infrastructure.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// Region where the cluster nodes will live.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// Link to a secret containing the service account JSON key.
        /// </summary>
        [Input("saKeyLink", required: true)]
        public Input<string> SaKeyLink { get; set; } = null!;

        [Input("tags")]
        private InputList<string>? _tags;
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public Mk8sGcpProviderGetArgs()
        {
        }
        public static new Mk8sGcpProviderGetArgs Empty => new Mk8sGcpProviderGetArgs();
    }
}
