// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class Mk8sAddOnsByokConfigIstioIngressGatewayGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CPU limit applied to ingress gateway pods.
        /// </summary>
        [Input("maxCpu")]
        public Input<string>? MaxCpu { get; set; }

        /// <summary>
        /// Memory limit applied to ingress gateway pods.
        /// </summary>
        [Input("maxMemory")]
        public Input<string>? MaxMemory { get; set; }

        /// <summary>
        /// Number of ingress gateway replicas.
        /// </summary>
        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        public Mk8sAddOnsByokConfigIstioIngressGatewayGetArgs()
        {
        }
        public static new Mk8sAddOnsByokConfigIstioIngressGatewayGetArgs Empty => new Mk8sAddOnsByokConfigIstioIngressGatewayGetArgs();
    }
}
