// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class OrgLoggingOpentelemetryLoggingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Full link to a secret of type `Opaque`.
        /// </summary>
        [Input("credentials")]
        public Input<string>? Credentials { get; set; }

        /// <summary>
        /// OpenTelemetry collector endpoint URI.
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// Custom headers to include in OpenTelemetry export requests.
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        public OrgLoggingOpentelemetryLoggingArgs()
        {
        }
        public static new OrgLoggingOpentelemetryLoggingArgs Empty => new OrgLoggingOpentelemetryLoggingArgs();
    }
}
