// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class OrgLoggingLokiLoggingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Full link to a secret of type `Userpass`. For Grafana Cloud, set the username to the instance ID and the password to an access token.
        /// </summary>
        [Input("credentials")]
        public Input<string>? Credentials { get; set; }

        /// <summary>
        /// Loki endpoint to push logs to (e.g. `https://logs-prod-012.grafana.net`).
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        /// <summary>
        /// The `X-Scope-OrgID` header value used for self-hosted multi-tenant Loki.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        public OrgLoggingLokiLoggingGetArgs()
        {
        }
        public static new OrgLoggingLokiLoggingGetArgs Empty => new OrgLoggingLokiLoggingGetArgs();
    }
}
