// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class OrgLoggingCoralogixLoggingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// App name to be displayed in Coralogix dashboard.
        /// </summary>
        [Input("app")]
        public Input<string>? App { get; set; }

        /// <summary>
        /// Coralogix cluster URI.
        /// </summary>
        [Input("cluster", required: true)]
        public Input<string> Cluster { get; set; } = null!;

        /// <summary>
        /// Full link to referenced Opaque Secret.
        /// </summary>
        [Input("credentials", required: true)]
        public Input<string> Credentials { get; set; } = null!;

        /// <summary>
        /// Subsystem name to be displayed in Coralogix dashboard.
        /// </summary>
        [Input("subsystem")]
        public Input<string>? Subsystem { get; set; }

        public OrgLoggingCoralogixLoggingArgs()
        {
        }
        public static new OrgLoggingCoralogixLoggingArgs Empty => new OrgLoggingCoralogixLoggingArgs();
    }
}
