// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class OrgStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountLink")]
        public Input<string>? AccountLink { get; set; }

        [Input("active")]
        public Input<bool>? Active { get; set; }

        public OrgStatusArgs()
        {
        }
        public static new OrgStatusArgs Empty => new OrgStatusArgs();
    }
}
