// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class OrgSecurityThreatDetectionArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("minimumSeverity")]
        public Input<string>? MinimumSeverity { get; set; }

        [Input("syslog")]
        public Input<Inputs.OrgSecurityThreatDetectionSyslogArgs>? Syslog { get; set; }

        public OrgSecurityThreatDetectionArgs()
        {
        }
        public static new OrgSecurityThreatDetectionArgs Empty => new OrgSecurityThreatDetectionArgs();
    }
}
