// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class VolumeSetCustomEncryptionArgs : global::Pulumi.ResourceArgs
    {
        [Input("regions", required: true)]
        private InputMap<Inputs.VolumeSetCustomEncryptionRegionsArgs>? _regions;

        /// <summary>
        /// Map of region identifiers to encryption key configuration.
        /// </summary>
        public InputMap<Inputs.VolumeSetCustomEncryptionRegionsArgs> Regions
        {
            get => _regions ?? (_regions = new InputMap<Inputs.VolumeSetCustomEncryptionRegionsArgs>());
            set => _regions = value;
        }

        public VolumeSetCustomEncryptionArgs()
        {
        }
        public static new VolumeSetCustomEncryptionArgs Empty => new VolumeSetCustomEncryptionArgs();
    }
}
