// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerLifecyclePreStopGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("exec", required: true)]
        public Input<Inputs.WorkloadContainerLifecyclePreStopExecGetArgs> Exec { get; set; } = null!;

        public WorkloadContainerLifecyclePreStopGetArgs()
        {
        }
        public static new WorkloadContainerLifecyclePreStopGetArgs Empty => new WorkloadContainerLifecyclePreStopGetArgs();
    }
}
