// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadVmNetworkGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Network interface name. Default: `Default`.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public WorkloadVmNetworkGetArgs()
        {
        }
        public static new WorkloadVmNetworkGetArgs Empty => new WorkloadVmNetworkGetArgs();
    }
}
