// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadLocalOptionAutoscalingKedaAdvancedScalingModifiersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines the new activation target value to scale on for the composed metric.
        /// </summary>
        [Input("activationTarget")]
        public Input<string>? ActivationTarget { get; set; }

        /// <summary>
        /// Composes metrics together and allows them to be modified/manipulated. It accepts mathematical/conditional statements.
        /// </summary>
        [Input("formula")]
        public Input<string>? Formula { get; set; }

        /// <summary>
        /// Defines metric type used for this new composite-metric.
        /// </summary>
        [Input("metricType")]
        public Input<string>? MetricType { get; set; }

        /// <summary>
        /// Defines new target value to scale on for the composed metric.
        /// </summary>
        [Input("target")]
        public Input<string>? Target { get; set; }

        public WorkloadLocalOptionAutoscalingKedaAdvancedScalingModifiersArgs()
        {
        }
        public static new WorkloadLocalOptionAutoscalingKedaAdvancedScalingModifiersArgs Empty => new WorkloadLocalOptionAutoscalingKedaAdvancedScalingModifiersArgs();
    }
}
