// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerLivenessProbeExecArgs : global::Pulumi.ResourceArgs
    {
        [Input("commands", required: true)]
        private InputList<string>? _commands;
        public InputList<string> Commands
        {
            get => _commands ?? (_commands = new InputList<string>());
            set => _commands = value;
        }

        public WorkloadContainerLivenessProbeExecArgs()
        {
        }
        public static new WorkloadContainerLivenessProbeExecArgs Empty => new WorkloadContainerLivenessProbeExecArgs();
    }
}
