// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerLifecycleArgs : global::Pulumi.ResourceArgs
    {
        [Input("_sentinel")]
        public Input<bool>? _sentinel { get; set; }

        [Input("postStart")]
        public Input<Inputs.WorkloadContainerLifecyclePostStartArgs>? PostStart { get; set; }

        [Input("preStop")]
        public Input<Inputs.WorkloadContainerLifecyclePreStopArgs>? PreStop { get; set; }

        public WorkloadContainerLifecycleArgs()
        {
        }
        public static new WorkloadContainerLifecycleArgs Empty => new WorkloadContainerLifecycleArgs();
    }
}
