// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerGpuNvidiaArgs : global::Pulumi.ResourceArgs
    {
        [Input("model", required: true)]
        public Input<string> Model { get; set; } = null!;

        [Input("quantity", required: true)]
        public Input<int> Quantity { get; set; } = null!;

        public WorkloadContainerGpuNvidiaArgs()
        {
        }
        public static new WorkloadContainerGpuNvidiaArgs Empty => new WorkloadContainerGpuNvidiaArgs();
    }
}
