// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerLifecyclePostStartArgs : global::Pulumi.ResourceArgs
    {
        [Input("exec")]
        public Input<Inputs.WorkloadContainerLifecyclePostStartExecArgs>? Exec { get; set; }

        public WorkloadContainerLifecyclePostStartArgs()
        {
        }
        public static new WorkloadContainerLifecyclePostStartArgs Empty => new WorkloadContainerLifecyclePostStartArgs();
    }
}
