// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadVmClockGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Guest timezone. Default: `UTC`.
        /// </summary>
        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public WorkloadVmClockGetArgs()
        {
        }
        public static new WorkloadVmClockGetArgs Empty => new WorkloadVmClockGetArgs();
    }
}
