// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadJobArgs : global::Pulumi.ResourceArgs
    {
        [Input("activeDeadlineSeconds")]
        public Input<int>? ActiveDeadlineSeconds { get; set; }

        [Input("concurrencyPolicy")]
        public Input<string>? ConcurrencyPolicy { get; set; }

        [Input("historyLimit")]
        public Input<int>? HistoryLimit { get; set; }

        [Input("restartPolicy")]
        public Input<string>? RestartPolicy { get; set; }

        [Input("schedule", required: true)]
        public Input<string> Schedule { get; set; } = null!;

        public WorkloadJobArgs()
        {
        }
        public static new WorkloadJobArgs Empty => new WorkloadJobArgs();
    }
}
