// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadStatusResolvedImageArgs : global::Pulumi.ResourceArgs
    {
        [Input("errorMessages")]
        private InputList<string>? _errorMessages;
        public InputList<string> ErrorMessages
        {
            get => _errorMessages ?? (_errorMessages = new InputList<string>());
            set => _errorMessages = value;
        }

        [Input("images")]
        private InputList<Inputs.WorkloadStatusResolvedImageImageArgs>? _images;

        /// <summary>
        /// A list of images that were resolved.
        /// </summary>
        public InputList<Inputs.WorkloadStatusResolvedImageImageArgs> Images
        {
            get => _images ?? (_images = new InputList<Inputs.WorkloadStatusResolvedImageImageArgs>());
            set => _images = value;
        }

        /// <summary>
        /// UTC Time when the images were resolved.
        /// </summary>
        [Input("resolvedAt")]
        public Input<string>? ResolvedAt { get; set; }

        /// <summary>
        /// Workload version the images were resolved for.
        /// </summary>
        [Input("resolvedForVersion")]
        public Input<int>? ResolvedForVersion { get; set; }

        public WorkloadStatusResolvedImageArgs()
        {
        }
        public static new WorkloadStatusResolvedImageArgs Empty => new WorkloadStatusResolvedImageArgs();
    }
}
