// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadRolloutOptionsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("maxSurgeReplicas")]
        public Input<string>? MaxSurgeReplicas { get; set; }

        [Input("maxUnavailableReplicas")]
        public Input<string>? MaxUnavailableReplicas { get; set; }

        [Input("minReadySeconds")]
        public Input<int>? MinReadySeconds { get; set; }

        [Input("scalingPolicy")]
        public Input<string>? ScalingPolicy { get; set; }

        public WorkloadRolloutOptionsGetArgs()
        {
        }
        public static new WorkloadRolloutOptionsGetArgs Empty => new WorkloadRolloutOptionsGetArgs();
    }
}
