// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadVmArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessCredentials")]
        private InputList<Inputs.WorkloadVmAccessCredentialArgs>? _accessCredentials;

        /// <summary>
        /// SSH public keys injected at runtime via the guest agent or config drive.
        /// </summary>
        public InputList<Inputs.WorkloadVmAccessCredentialArgs> AccessCredentials
        {
            get => _accessCredentials ?? (_accessCredentials = new InputList<Inputs.WorkloadVmAccessCredentialArgs>());
            set => _accessCredentials = value;
        }

        /// <summary>
        /// Boot disk configuration. When `Source` is omitted, `containers[0].image` is used as an OCI containerDisk.
        /// </summary>
        [Input("bootDisk")]
        public Input<Inputs.WorkloadVmBootDiskArgs>? BootDisk { get; set; }

        /// <summary>
        /// Guest clock configuration. Defaults to `timezone = UTC` when omitted.
        /// </summary>
        [Input("clock")]
        public Input<Inputs.WorkloadVmClockArgs>? Clock { get; set; }

        /// <summary>
        /// Cloud-init configuration for the guest. Exactly one of `UserData`, `UserDataBase64`, or `UserDataSecret` must be specified.
        /// </summary>
        [Input("cloudInit")]
        public Input<Inputs.WorkloadVmCloudInitArgs>? CloudInit { get; set; }

        /// <summary>
        /// CPU topology visible to the guest. Cores are derived from `containers[0].cpu`.
        /// </summary>
        [Input("cpu")]
        public Input<Inputs.WorkloadVmCpuArgs>? Cpu { get; set; }

        /// <summary>
        /// Firmware configuration for the guest. Defaults to `bootloader = efi` and `SecureBoot = false` when omitted.
        /// </summary>
        [Input("firmware")]
        public Input<Inputs.WorkloadVmFirmwareArgs>? Firmware { get; set; }

        /// <summary>
        /// Guest operating system family. Drives the per-OS cloud-init payload. Valid values: `Linux`, `Windows`. Default: `Linux`.
        /// </summary>
        [Input("guestOs")]
        public Input<string>? GuestOs { get; set; }

        /// <summary>
        /// Hostname reported to the guest.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        [Input("networks")]
        private InputList<Inputs.WorkloadVmNetworkArgs>? _networks;

        /// <summary>
        /// Pod-network interfaces for the VM. Only a single network is supported. Defaults to a single `Default` network when omitted.
        /// </summary>
        public InputList<Inputs.WorkloadVmNetworkArgs> Networks
        {
            get => _networks ?? (_networks = new InputList<Inputs.WorkloadVmNetworkArgs>());
            set => _networks = value;
        }

        /// <summary>
        /// KubeVirt RunStrategy. Use `Halted` to keep the pool defined but powered off. Valid values: `Always`, `RerunOnFailure`, `Manual`, `Halted`. Default: `Always`.
        /// </summary>
        [Input("runStrategy")]
        public Input<string>? RunStrategy { get; set; }

        /// <summary>
        /// Subdomain used by the guest for replica-to-replica addressing.
        /// </summary>
        [Input("subdomain")]
        public Input<string>? Subdomain { get; set; }

        public WorkloadVmArgs()
        {
        }
        public static new WorkloadVmArgs Empty => new WorkloadVmArgs();
    }
}
