// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadStatusHealthCheckGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("active", required: true)]
        public Input<bool> Active { get; set; } = null!;

        [Input("code")]
        public Input<int>? Code { get; set; }

        [Input("failures")]
        public Input<int>? Failures { get; set; }

        [Input("lastChecked")]
        public Input<string>? LastChecked { get; set; }

        [Input("message")]
        public Input<string>? Message { get; set; }

        [Input("success")]
        public Input<bool>? Success { get; set; }

        [Input("successes")]
        public Input<int>? Successes { get; set; }

        public WorkloadStatusHealthCheckGetArgs()
        {
        }
        public static new WorkloadStatusHealthCheckGetArgs Empty => new WorkloadStatusHealthCheckGetArgs();
    }
}
