// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerGpuNvidiaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GPU Model (i.e.: t4)
        /// </summary>
        [Input("model", required: true)]
        public Input<string> Model { get; set; } = null!;

        /// <summary>
        /// Number of GPUs.
        /// </summary>
        [Input("quantity", required: true)]
        public Input<int> Quantity { get; set; } = null!;

        public WorkloadContainerGpuNvidiaGetArgs()
        {
        }
        public static new WorkloadContainerGpuNvidiaGetArgs Empty => new WorkloadContainerGpuNvidiaGetArgs();
    }
}
