// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadContainerMetricsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path from container emitting custom metrics.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// Port from container emitting custom metrics.
        /// </summary>
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        public WorkloadContainerMetricsArgs()
        {
        }
        public static new WorkloadContainerMetricsArgs Empty => new WorkloadContainerMetricsArgs();
    }
}
