// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadOptionsAutoscalingMultiGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("metric")]
        public Input<string>? Metric { get; set; }

        [Input("target")]
        public Input<int>? Target { get; set; }

        public WorkloadOptionsAutoscalingMultiGetArgs()
        {
        }
        public static new WorkloadOptionsAutoscalingMultiGetArgs Empty => new WorkloadOptionsAutoscalingMultiGetArgs();
    }
}
