// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadStatusResolvedImageImageGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("digest")]
        public Input<string>? Digest { get; set; }

        [Input("manifests")]
        private InputList<Inputs.WorkloadStatusResolvedImageImageManifestGetArgs>? _manifests;
        public InputList<Inputs.WorkloadStatusResolvedImageImageManifestGetArgs> Manifests
        {
            get => _manifests ?? (_manifests = new InputList<Inputs.WorkloadStatusResolvedImageImageManifestGetArgs>());
            set => _manifests = value;
        }

        public WorkloadStatusResolvedImageImageGetArgs()
        {
        }
        public static new WorkloadStatusResolvedImageImageGetArgs Empty => new WorkloadStatusResolvedImageImageGetArgs();
    }
}
