// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cpln.Inputs
{

    public sealed class WorkloadVmFirmwareSmbiosArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SMBIOS system family.
        /// </summary>
        [Input("family")]
        public Input<string>? Family { get; set; }

        /// <summary>
        /// SMBIOS system manufacturer.
        /// </summary>
        [Input("manufacturer")]
        public Input<string>? Manufacturer { get; set; }

        /// <summary>
        /// SMBIOS system product name.
        /// </summary>
        [Input("product")]
        public Input<string>? Product { get; set; }

        /// <summary>
        /// SMBIOS system SKU.
        /// </summary>
        [Input("sku")]
        public Input<string>? Sku { get; set; }

        /// <summary>
        /// SMBIOS system version.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public WorkloadVmFirmwareSmbiosArgs()
        {
        }
        public static new WorkloadVmFirmwareSmbiosArgs Empty => new WorkloadVmFirmwareSmbiosArgs();
    }
}
