name: Upgrade provider
on:
  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@main
        with:
          # Upgrading all libs increases the chance of the build to fail.
          # So, we upgrade only provider to reduce the number of human interventions.
          kind: provider
          username: pulumi-bot
          email: bot@pulumi.com
