// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AuditContext extends pulumi.CustomResource {
    /**
     * Get an existing AuditContext resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AuditContextState, opts?: pulumi.CustomResourceOptions): AuditContext {
        return new AuditContext(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cpln:index/auditContext:AuditContext';

    /**
     * Returns true if the given object is an instance of AuditContext.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AuditContext {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AuditContext.__pulumiType;
    }

    /**
     * The ID, in GUID format, of the Audit Context.
     */
    declare public /*out*/ readonly cplnId: pulumi.Output<string>;
    /**
     * Description of the Audit Context.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Name of the Audit Context.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly origin: pulumi.Output<string>;
    /**
     * Full link to this resource. Can be referenced by other resources.
     */
    declare public /*out*/ readonly selfLink: pulumi.Output<string>;
    /**
     * Key-value map of resource tags.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string}>;

    /**
     * Create a AuditContext resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AuditContextArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AuditContextArgs | AuditContextState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AuditContextState | undefined;
            resourceInputs["cplnId"] = state?.cplnId;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["origin"] = state?.origin;
            resourceInputs["selfLink"] = state?.selfLink;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as AuditContextArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["cplnId"] = undefined /*out*/;
            resourceInputs["origin"] = undefined /*out*/;
            resourceInputs["selfLink"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AuditContext.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AuditContext resources.
 */
export interface AuditContextState {
    /**
     * The ID, in GUID format, of the Audit Context.
     */
    cplnId?: pulumi.Input<string>;
    /**
     * Description of the Audit Context.
     */
    description?: pulumi.Input<string>;
    /**
     * Name of the Audit Context.
     */
    name?: pulumi.Input<string>;
    origin?: pulumi.Input<string>;
    /**
     * Full link to this resource. Can be referenced by other resources.
     */
    selfLink?: pulumi.Input<string>;
    /**
     * Key-value map of resource tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a AuditContext resource.
 */
export interface AuditContextArgs {
    /**
     * Description of the Audit Context.
     */
    description?: pulumi.Input<string>;
    /**
     * Name of the Audit Context.
     */
    name?: pulumi.Input<string>;
    /**
     * Key-value map of resource tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
