// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CatalogTemplate extends pulumi.CustomResource {
    /**
     * Get an existing CatalogTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CatalogTemplateState, opts?: pulumi.CustomResourceOptions): CatalogTemplate {
        return new CatalogTemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cpln:index/catalogTemplate:CatalogTemplate';

    /**
     * Returns true if the given object is an instance of CatalogTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CatalogTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CatalogTemplate.__pulumiType;
    }

    /**
     * The GVC where the template will be deployed. Leave empty if the template creates its own GVC (check template's createsGvc field).
     */
    declare public readonly gvc: pulumi.Output<string>;
    /**
     * The release name for this catalog release.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * List of Control Plane resources created by this release. Populated from the helm release secret.
     */
    declare public /*out*/ readonly resources: pulumi.Output<outputs.CatalogTemplateResource[]>;
    /**
     * The name of the catalog template to deploy (e.g., 'postgres', 'nginx', 'redis').
     */
    declare public readonly template: pulumi.Output<string>;
    /**
     * The values file content (YAML format) for customizing the template deployment.
     */
    declare public readonly values: pulumi.Output<string>;
    /**
     * The version of the catalog template to deploy.
     */
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a CatalogTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CatalogTemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CatalogTemplateArgs | CatalogTemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CatalogTemplateState | undefined;
            resourceInputs["gvc"] = state?.gvc;
            resourceInputs["name"] = state?.name;
            resourceInputs["resources"] = state?.resources;
            resourceInputs["template"] = state?.template;
            resourceInputs["values"] = state?.values;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as CatalogTemplateArgs | undefined;
            if (args?.template === undefined && !opts.urn) {
                throw new Error("Missing required property 'template'");
            }
            if (args?.values === undefined && !opts.urn) {
                throw new Error("Missing required property 'values'");
            }
            if (args?.version === undefined && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["gvc"] = args?.gvc;
            resourceInputs["name"] = args?.name;
            resourceInputs["template"] = args?.template;
            resourceInputs["values"] = args?.values;
            resourceInputs["version"] = args?.version;
            resourceInputs["resources"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CatalogTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CatalogTemplate resources.
 */
export interface CatalogTemplateState {
    /**
     * The GVC where the template will be deployed. Leave empty if the template creates its own GVC (check template's createsGvc field).
     */
    gvc?: pulumi.Input<string>;
    /**
     * The release name for this catalog release.
     */
    name?: pulumi.Input<string>;
    /**
     * List of Control Plane resources created by this release. Populated from the helm release secret.
     */
    resources?: pulumi.Input<pulumi.Input<inputs.CatalogTemplateResource>[]>;
    /**
     * The name of the catalog template to deploy (e.g., 'postgres', 'nginx', 'redis').
     */
    template?: pulumi.Input<string>;
    /**
     * The values file content (YAML format) for customizing the template deployment.
     */
    values?: pulumi.Input<string>;
    /**
     * The version of the catalog template to deploy.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CatalogTemplate resource.
 */
export interface CatalogTemplateArgs {
    /**
     * The GVC where the template will be deployed. Leave empty if the template creates its own GVC (check template's createsGvc field).
     */
    gvc?: pulumi.Input<string>;
    /**
     * The release name for this catalog release.
     */
    name?: pulumi.Input<string>;
    /**
     * The name of the catalog template to deploy (e.g., 'postgres', 'nginx', 'redis').
     */
    template: pulumi.Input<string>;
    /**
     * The values file content (YAML format) for customizing the template deployment.
     */
    values: pulumi.Input<string>;
    /**
     * The version of the catalog template to deploy.
     */
    version: pulumi.Input<string>;
}
