// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CustomLocation extends pulumi.CustomResource {
    /**
     * Get an existing CustomLocation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomLocationState, opts?: pulumi.CustomResourceOptions): CustomLocation {
        return new CustomLocation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cpln:index/customLocation:CustomLocation';

    /**
     * Returns true if the given object is an instance of CustomLocation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomLocation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomLocation.__pulumiType;
    }

    /**
     * Cloud Provider of the custom location.
     */
    declare public readonly cloudProvider: pulumi.Output<string>;
    /**
     * The ID, in GUID format, of the Custom Location.
     */
    declare public /*out*/ readonly cplnId: pulumi.Output<string>;
    /**
     * Description of the Custom Location.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Indication if the custom location is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Name of the Custom Location.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly origin: pulumi.Output<string>;
    /**
     * Region of the location.
     */
    declare public /*out*/ readonly region: pulumi.Output<string>;
    /**
     * Full link to this resource. Can be referenced by other resources.
     */
    declare public /*out*/ readonly selfLink: pulumi.Output<string>;
    /**
     * Key-value map of resource tags.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string}>;

    /**
     * Create a CustomLocation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomLocationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomLocationArgs | CustomLocationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomLocationState | undefined;
            resourceInputs["cloudProvider"] = state?.cloudProvider;
            resourceInputs["cplnId"] = state?.cplnId;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["origin"] = state?.origin;
            resourceInputs["region"] = state?.region;
            resourceInputs["selfLink"] = state?.selfLink;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as CustomLocationArgs | undefined;
            if (args?.cloudProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudProvider'");
            }
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            resourceInputs["cloudProvider"] = args?.cloudProvider;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["cplnId"] = undefined /*out*/;
            resourceInputs["origin"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["selfLink"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomLocation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomLocation resources.
 */
export interface CustomLocationState {
    /**
     * Cloud Provider of the custom location.
     */
    cloudProvider?: pulumi.Input<string>;
    /**
     * The ID, in GUID format, of the Custom Location.
     */
    cplnId?: pulumi.Input<string>;
    /**
     * Description of the Custom Location.
     */
    description?: pulumi.Input<string>;
    /**
     * Indication if the custom location is enabled.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Name of the Custom Location.
     */
    name?: pulumi.Input<string>;
    origin?: pulumi.Input<string>;
    /**
     * Region of the location.
     */
    region?: pulumi.Input<string>;
    /**
     * Full link to this resource. Can be referenced by other resources.
     */
    selfLink?: pulumi.Input<string>;
    /**
     * Key-value map of resource tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a CustomLocation resource.
 */
export interface CustomLocationArgs {
    /**
     * Cloud Provider of the custom location.
     */
    cloudProvider: pulumi.Input<string>;
    /**
     * Description of the Custom Location.
     */
    description?: pulumi.Input<string>;
    /**
     * Indication if the custom location is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * Name of the Custom Location.
     */
    name?: pulumi.Input<string>;
    /**
     * Key-value map of resource tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
