// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Org extends pulumi.CustomResource {
    /**
     * Get an existing Org resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgState, opts?: pulumi.CustomResourceOptions): Org {
        return new Org(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cpln:index/org:Org';

    /**
     * Returns true if the given object is an instance of Org.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Org {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Org.__pulumiType;
    }

    public readonly accountId!: pulumi.Output<string | undefined>;
    public readonly authConfig!: pulumi.Output<outputs.OrgAuthConfig | undefined>;
    public /*out*/ readonly cplnId!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly invitees!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly name!: pulumi.Output<string>;
    public readonly observability!: pulumi.Output<outputs.OrgObservability>;
    public /*out*/ readonly selfLink!: pulumi.Output<string>;
    public readonly sessionTimeoutSeconds!: pulumi.Output<number | undefined>;
    public /*out*/ readonly statuses!: pulumi.Output<outputs.OrgStatus[]>;
    public readonly tags!: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a Org resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrgArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgArgs | OrgState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgState | undefined;
            resourceInputs["accountId"] = state ? state.accountId : undefined;
            resourceInputs["authConfig"] = state ? state.authConfig : undefined;
            resourceInputs["cplnId"] = state ? state.cplnId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["invitees"] = state ? state.invitees : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["observability"] = state ? state.observability : undefined;
            resourceInputs["selfLink"] = state ? state.selfLink : undefined;
            resourceInputs["sessionTimeoutSeconds"] = state ? state.sessionTimeoutSeconds : undefined;
            resourceInputs["statuses"] = state ? state.statuses : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as OrgArgs | undefined;
            if ((!args || args.observability === undefined) && !opts.urn) {
                throw new Error("Missing required property 'observability'");
            }
            resourceInputs["accountId"] = args ? args.accountId : undefined;
            resourceInputs["authConfig"] = args ? args.authConfig : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["invitees"] = args ? args.invitees : undefined;
            resourceInputs["observability"] = args ? args.observability : undefined;
            resourceInputs["sessionTimeoutSeconds"] = args ? args.sessionTimeoutSeconds : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["cplnId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["selfLink"] = undefined /*out*/;
            resourceInputs["statuses"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Org.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Org resources.
 */
export interface OrgState {
    accountId?: pulumi.Input<string>;
    authConfig?: pulumi.Input<inputs.OrgAuthConfig>;
    cplnId?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    invitees?: pulumi.Input<pulumi.Input<string>[]>;
    name?: pulumi.Input<string>;
    observability?: pulumi.Input<inputs.OrgObservability>;
    selfLink?: pulumi.Input<string>;
    sessionTimeoutSeconds?: pulumi.Input<number>;
    statuses?: pulumi.Input<pulumi.Input<inputs.OrgStatus>[]>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a Org resource.
 */
export interface OrgArgs {
    accountId?: pulumi.Input<string>;
    authConfig?: pulumi.Input<inputs.OrgAuthConfig>;
    description?: pulumi.Input<string>;
    invitees?: pulumi.Input<pulumi.Input<string>[]>;
    observability: pulumi.Input<inputs.OrgObservability>;
    sessionTimeoutSeconds?: pulumi.Input<number>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
