// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class OrgLogging extends pulumi.CustomResource {
    /**
     * Get an existing OrgLogging resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgLoggingState, opts?: pulumi.CustomResourceOptions): OrgLogging {
        return new OrgLogging(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cpln:index/orgLogging:OrgLogging';

    /**
     * Returns true if the given object is an instance of OrgLogging.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrgLogging {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrgLogging.__pulumiType;
    }

    public readonly cloudWatchLoggings!: pulumi.Output<outputs.OrgLoggingCloudWatchLogging[] | undefined>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/coralogix)
     */
    public readonly coralogixLoggings!: pulumi.Output<outputs.OrgLoggingCoralogixLogging[] | undefined>;
    /**
     * The ID, in GUID format, of the org.
     */
    public /*out*/ readonly cplnId!: pulumi.Output<string>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/datadog)
     */
    public readonly datadogLoggings!: pulumi.Output<outputs.OrgLoggingDatadogLogging[] | undefined>;
    /**
     * The description of org.
     */
    public /*out*/ readonly description!: pulumi.Output<string>;
    public readonly elasticLoggings!: pulumi.Output<outputs.OrgLoggingElasticLogging[] | undefined>;
    public readonly fluentdLoggings!: pulumi.Output<outputs.OrgLoggingFluentdLogging[] | undefined>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/logz-io)
     */
    public readonly logzioLoggings!: pulumi.Output<outputs.OrgLoggingLogzioLogging[] | undefined>;
    /**
     * The name of the org.
     */
    public /*out*/ readonly name!: pulumi.Output<string>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/s3)
     */
    public readonly s3Loggings!: pulumi.Output<outputs.OrgLoggingS3Logging[] | undefined>;
    public readonly stackdriverLoggings!: pulumi.Output<outputs.OrgLoggingStackdriverLogging[] | undefined>;
    public readonly syslogLoggings!: pulumi.Output<outputs.OrgLoggingSyslogLogging[] | undefined>;
    /**
     * Key-value map of the org's tags.
     */
    public /*out*/ readonly tags!: pulumi.Output<{[key: string]: string}>;

    /**
     * Create a OrgLogging resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OrgLoggingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgLoggingArgs | OrgLoggingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgLoggingState | undefined;
            resourceInputs["cloudWatchLoggings"] = state ? state.cloudWatchLoggings : undefined;
            resourceInputs["coralogixLoggings"] = state ? state.coralogixLoggings : undefined;
            resourceInputs["cplnId"] = state ? state.cplnId : undefined;
            resourceInputs["datadogLoggings"] = state ? state.datadogLoggings : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["elasticLoggings"] = state ? state.elasticLoggings : undefined;
            resourceInputs["fluentdLoggings"] = state ? state.fluentdLoggings : undefined;
            resourceInputs["logzioLoggings"] = state ? state.logzioLoggings : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["s3Loggings"] = state ? state.s3Loggings : undefined;
            resourceInputs["stackdriverLoggings"] = state ? state.stackdriverLoggings : undefined;
            resourceInputs["syslogLoggings"] = state ? state.syslogLoggings : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as OrgLoggingArgs | undefined;
            resourceInputs["cloudWatchLoggings"] = args ? args.cloudWatchLoggings : undefined;
            resourceInputs["coralogixLoggings"] = args ? args.coralogixLoggings : undefined;
            resourceInputs["datadogLoggings"] = args ? args.datadogLoggings : undefined;
            resourceInputs["elasticLoggings"] = args ? args.elasticLoggings : undefined;
            resourceInputs["fluentdLoggings"] = args ? args.fluentdLoggings : undefined;
            resourceInputs["logzioLoggings"] = args ? args.logzioLoggings : undefined;
            resourceInputs["s3Loggings"] = args ? args.s3Loggings : undefined;
            resourceInputs["stackdriverLoggings"] = args ? args.stackdriverLoggings : undefined;
            resourceInputs["syslogLoggings"] = args ? args.syslogLoggings : undefined;
            resourceInputs["cplnId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrgLogging.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OrgLogging resources.
 */
export interface OrgLoggingState {
    cloudWatchLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingCloudWatchLogging>[]>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/coralogix)
     */
    coralogixLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingCoralogixLogging>[]>;
    /**
     * The ID, in GUID format, of the org.
     */
    cplnId?: pulumi.Input<string>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/datadog)
     */
    datadogLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingDatadogLogging>[]>;
    /**
     * The description of org.
     */
    description?: pulumi.Input<string>;
    elasticLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingElasticLogging>[]>;
    fluentdLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingFluentdLogging>[]>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/logz-io)
     */
    logzioLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingLogzioLogging>[]>;
    /**
     * The name of the org.
     */
    name?: pulumi.Input<string>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/s3)
     */
    s3Loggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingS3Logging>[]>;
    stackdriverLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingStackdriverLogging>[]>;
    syslogLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingSyslogLogging>[]>;
    /**
     * Key-value map of the org's tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a OrgLogging resource.
 */
export interface OrgLoggingArgs {
    cloudWatchLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingCloudWatchLogging>[]>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/coralogix)
     */
    coralogixLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingCoralogixLogging>[]>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/datadog)
     */
    datadogLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingDatadogLogging>[]>;
    elasticLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingElasticLogging>[]>;
    fluentdLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingFluentdLogging>[]>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/logz-io)
     */
    logzioLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingLogzioLogging>[]>;
    /**
     * [Documentation Reference](https://docs.controlplane.com/external-logging/s3)
     */
    s3Loggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingS3Logging>[]>;
    stackdriverLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingStackdriverLogging>[]>;
    syslogLoggings?: pulumi.Input<pulumi.Input<inputs.OrgLoggingSyslogLogging>[]>;
}
